import { Router } from "express";
import { BuyersController as c } from "../controllers/buyers.controller.js";
import { requiresAuth, requiresPermission } from "../middlewares.js";
import multer from "multer";
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024}});
const router=Router(); router.use(requiresAuth);
router.get("/masters",requiresPermission("buyers","read"),c.masters);
router.get("/bulk-upload/template",requiresPermission("buyers","read"),c.downloadTemplate);
router.post("/bulk-upload/analyze",requiresPermission("buyers","create"),upload.single("file"),c.analyzeUpload);
router.post("/bulk-upload",requiresPermission("buyers","create"),upload.single("file"),c.bulkUpload);
router.get("/",requiresPermission("buyers","read"),c.list); router.get("/:id",requiresPermission("buyers","read"),c.get);
router.post("/",requiresPermission("buyers","create"),c.create); router.put("/:id",requiresPermission("buyers","update"),c.update); router.delete("/:id",requiresPermission("buyers","delete"),c.remove);
router.post("/:id/contacts",requiresPermission("buyers","update"),c.addContact); router.put("/:id/contacts/:contactId",requiresPermission("buyers","update"),c.updateContact);
router.post("/:id/locations",requiresPermission("buyers","update"),c.addLocation);
export default router;
