import ExcelJS from"exceljs";import{query}from"../db.js";import{safeJson}from"../utils.js";
const sources={
 sales:{category:"Sales",label:"Sales & Revenue",view:"finance_commercial_register_view",fields:["commercial_number","order_number","order_date","state","buyer_name","supplier_name","sales_representative","product_category","grade","quantity_kg","gross_revenue","gross_profit","net_profit","net_margin_percent","commercial_status"]},
 inquiries:{category:"Sales",label:"Inquiry Conversion & Pipeline",view:"sales_transactions",fields:["inquiry_number","inquiry_type","inquiry_source","inquiry_date","current_stage","status","sales_representative","created_at","updated_at"]},
 orders:{category:"Sales",label:"Order Volume",view:"orders",fields:["order_number","order_date","product_category","grade","quantity_kg","total_order_value","gross_margin","status","expected_delivery_date","buyer_id","supplier_id"]},
 suppliers:{category:"Procurement",label:"Supplier Performance",view:"suppliers",fields:["group_name","country","supplier_tag","primary_contact_name","email","is_active","created_at"]},
 procurement:{category:"Procurement",label:"Purchase Trends & Price Comparison",view:"supplier_grade_prices",fields:["grade_id","purchase_price","remarks","effective_at","expires_at","is_active","created_at"]},
 logistics:{category:"Logistics",label:"Freight, Transporter & Route Profitability",view:"logistics_cost_register",fields:["order_reference","invoice_number","freight_cost","door_delivery_charges","porter_charges","other_charges","total_logistics_cost","created_at"]},
 finance:{category:"Finance",label:"Revenue, Profitability & Cash",view:"finance_commercial_register_view",fields:["commercial_number","state","buyer_name","supplier_name","order_number","buyer_invoice_number","order_date","gross_revenue","cogs","total_logistics_cost","gross_profit","net_profit","net_margin_percent","amount_received","outstanding_amount","days_outstanding"]},
 receivables:{category:"Finance",label:"Receivables & Credit Exposure",view:"finance_receivables_view",fields:["buyer","invoice_number","invoice_date","invoice_value","due_date","amount_received","outstanding","days_outstanding","ageing_bucket","status"]},
 payables:{category:"Finance",label:"Payables",view:"finance_payables_view",fields:["supplier","supplier_invoice_number","invoice_date","purchase_value","due_date","amount_paid","outstanding","days_outstanding","status"]},
 customers:{category:"Customer",label:"Profitability, Ranking, Repeat Orders & Industry",view:"buyers",fields:["group_name","state","group_tag","lead_type","lifecycle_status","order_count","monthly_consumption","total_revenue","latest_quoted_price","credit_limit","internal_credit_rating"]}
};
const ident=(source,name)=>{if(!sources[source]?.fields.includes(name))throw new Error(`Unsupported field: ${name}`);return `"${name}"`};
const ops={eq:"=",ne:"<>",gt:">",gte:">=",lt:"<",lte:"<=",contains:"ILIKE"};
function formula(source,f){if(!/^[a-z_][a-z0-9_]*$/i.test(f.alias||""))throw new Error("Invalid formula alias.");if(!/^[a-z0-9_+*/().\s-]+$/i.test(f.expression||""))throw new Error("Formula contains unsupported characters.");const expression=f.expression.replace(/[a-z_][a-z0-9_]*/gi,x=>ident(source,x));return`(${expression}) AS "${f.alias}"`}
function build(c={}){const s=sources[c.data_source];if(!s)throw new Error("Invalid data source.");const group=(c.grouping||[]).filter(x=>s.fields.includes(x)),aggs=(c.aggregations||[]).filter(x=>s.fields.includes(x.field)&&["sum","avg","min","max","count"].includes(x.function)),formulas=(c.formula_fields||[]).map(x=>formula(c.data_source,x));let select=(c.selected_fields||[]).filter(x=>s.fields.includes(x));if(group.length||aggs.length)select=[...group,...aggs.map((x,i)=>`${x.function}("${x.field}") AS "${x.alias||`${x.function}_${x.field}_${i}`}"`)];else select=[...select,...formulas];if(!select.length)select=s.fields;const values=[],where=[];for(const f of c.filters||[]){if(!s.fields.includes(f.field)||!ops[f.operator])continue;values.push(f.operator==="contains"?`%${f.value}%`:f.value);where.push(`"${f.field}" ${ops[f.operator]} $${values.length}`)}const order=(c.sorting||[]).filter(x=>s.fields.includes(x.field)).map(x=>`"${x.field}" ${x.direction==="desc"?"DESC":"ASC"}`);const sql=`SELECT ${select.map(x=>x.includes("(")?x:ident(c.data_source,x)).join(",")} FROM ${s.view}${where.length?` WHERE ${where.join(" AND ")}`:""}${group.length?` GROUP BY ${group.map(x=>ident(c.data_source,x)).join(",")}`:""}${order.length?` ORDER BY ${order.join(",")}`:""} LIMIT ${Math.min(+c.limit||1000,5000)}`;return{sql,values}}
const rows=async(sql,p=[])=>(await query(sql,p)).rows.map(safeJson);
function csv(data){if(!data.length)return Buffer.from("");const h=Object.keys(data[0]),esc=x=>`"${String(x??"").replaceAll('"','""')}"`;return Buffer.from([h.map(esc).join(","),...data.map(r=>h.map(k=>esc(r[k])).join(","))].join("\n"))}
function pdf(data,title){const lines=[title,"",...(data.length?[Object.keys(data[0]).join(" | "),...data.slice(0,45).map(r=>Object.values(r).map(x=>String(x??"").slice(0,18)).join(" | "))]:["No data"])].map(x=>x.replace(/[()\\]/g,"\\$&").replace(/[^\x20-\x7E]/g,"?"));const stream=`BT /F1 8 Tf 35 800 Td ${lines.map((x,i)=>`${i?'0 -15 Td ':''}(${x.slice(0,150)}) Tj`).join(" ")} ET`,objs=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`,`<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>`];let out="%PDF-1.4\n",offset=[0];objs.forEach((o,i)=>{offset.push(Buffer.byteLength(out));out+=`${i+1} 0 obj\n${o}\nendobj\n`});const start=Buffer.byteLength(out);out+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n${offset.slice(1).map(x=>String(x).padStart(10,"0")+" 00000 n \n").join("")}trailer << /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return Buffer.from(out)}
export const BIService={
 catalog(){return Object.entries(sources).map(([key,x])=>({key,...x}))},async reports(){return rows("SELECT r.*,u.name created_by_name FROM bi_report_definitions r LEFT JOIN users u ON u.id=r.created_by WHERE r.is_active ORDER BY r.category,r.name")},async saveReport(id,p,user){const fields=["name","category","data_source","description","selected_fields","filters","grouping","sorting","formula_fields","aggregations","pivot_config","chart_config","is_active"].filter(x=>p[x]!==undefined),v=fields.map(x=>p[x]);if(id){v.push(user,id);return safeJson((await query(`UPDATE bi_report_definitions SET ${fields.map((x,i)=>`${x}=$${i+1}`).join(",")},updated_by=$${v.length-1},updated_at=now()WHERE id=$${v.length} RETURNING *`,v)).rows[0])}v.push(user);return safeJson((await query(`INSERT INTO bi_report_definitions(${fields.join(",")},created_by,updated_by)VALUES(${fields.map((_,i)=>`$${i+1}`).join(",")},$${v.length},$${v.length})RETURNING *`,v)).rows[0])},
 async run(c){const q=build(c);return rows(q.sql,q.values)},async export(c,format){const data=await this.run(c);if(format==="csv")return{buffer:csv(data),type:"text/csv",ext:"csv"};if(format==="pdf")return{buffer:pdf(data,c.name||"Cresco BI Report"),type:"application/pdf",ext:"pdf"};const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet("Report"),keys=data[0]?Object.keys(data[0]):[];ws.columns=keys.map(k=>({header:k.replaceAll("_"," ").toUpperCase(),key:k,width:20}));ws.addRows(data);if(keys.length){ws.views=[{state:"frozen",ySplit:1}];ws.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};ws.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF0F4C5C"}};ws.autoFilter={from:{row:1,column:1},to:{row:1,column:keys.length}}}return{buffer:Buffer.from(await wb.xlsx.writeBuffer()),type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",ext:"xlsx"}},
 async dashboards(){return rows("SELECT d.*,COALESCE(json_agg(w ORDER BY w.position)FILTER(WHERE w.id IS NOT NULL),'[]')widgets FROM bi_dashboards d LEFT JOIN bi_dashboard_widgets w ON w.dashboard_id=d.id GROUP BY d.id ORDER BY d.is_default DESC,d.name")},async saveDashboard(p,user){return safeJson((await query("INSERT INTO bi_dashboards(name,description,is_default,is_shared,owner_id)VALUES($1,$2,$3,$4,$5)RETURNING *",[p.name,p.description,p.is_default||false,p.is_shared||false,user])).rows[0])},async addWidget(id,p){return safeJson((await query("INSERT INTO bi_dashboard_widgets(dashboard_id,report_id,title,widget_type,configuration,position,width,height)VALUES($1,$2,$3,$4,$5,$6,$7,$8)RETURNING *",[id,p.report_id||null,p.title,p.widget_type,p.configuration||{},p.position||0,p.width||1,p.height||1])).rows[0])},async reorder(id,widgets){for(const[x,i]of widgets.entries())await query("UPDATE bi_dashboard_widgets SET position=$1,updated_at=now()WHERE id=$2 AND dashboard_id=$3",[i,x.id,id]);return{message:"Dashboard layout saved."}},
 async schedules(){return rows("SELECT s.*,r.name report_name FROM bi_report_schedules s JOIN bi_report_definitions r ON r.id=s.report_id ORDER BY s.created_at DESC")},async saveSchedule(p,user){return safeJson((await query("INSERT INTO bi_report_schedules(report_id,name,frequency,day_of_month,delivery_time,timezone,recipients,export_format,is_active,created_by,next_run_at)VALUES($1,$2,'Monthly',$3,$4,$5,$6,$7,$8,$9,date_trunc('month',now())+interval '1 month'+make_interval(days=>$3-1)+(extract(epoch from $4::time)*interval '1 second'))RETURNING *",[p.report_id,p.name,p.day_of_month||1,p.delivery_time||"09:00",p.timezone||"Asia/Kolkata",p.recipients||[],p.export_format||"xlsx",p.is_active!==false,user])).rows[0])}
};
