import {getClient,query} from "../db.js";
import {safeJson} from "../utils.js";
import {NotificationsService} from "./notifications.service.js";
const bad=(message,status=400)=>Object.assign(new Error(message),{status});
const registerSql=`SELECT a.id account_id,a.receivable_id,a.buyer_id,b.group_name buyer,a.buyer_gst,r.invoice_number,r.invoice_date,a.invoice_value,a.gst_amount,a.value_excluding_gst,a.delivery_date,a.payment_terms,a.credit_days,a.due_date,a.grace_period_days,a.first_chargeable_date,
 COALESCE(v.outstanding,0) current_outstanding,GREATEST(CURRENT_DATE-a.due_date-a.grace_period_days,0) overdue_days,
 COALESCE(last.daily_rate_percent,s.daily_rate_percent) daily_charge_rate,COALESCE(last.daily_charge,0) daily_charge,COALESCE(last.cumulative_accrued,0) total_accrued_charge,
 COALESCE(notes.approved,0) previously_debited_charge,GREATEST(COALESCE(last.cumulative_accrued,0)-COALESCE(notes.approved,0),0) unbilled_accrued_charge,
 pay.last_payment_date payment_date,CASE WHEN COALESCE(v.outstanding,0)<=0 THEN'Settled'WHEN CURRENT_DATE>a.due_date THEN'Overdue'ELSE'Outstanding'END payment_status,
 CASE WHEN notes.pending>0 THEN'Pending Final Approval'WHEN notes.approved>0 THEN'Approved'WHEN GREATEST(COALESCE(last.cumulative_accrued,0)-COALESCE(notes.approved,0),0)>0 THEN'Debit Available'ELSE'No Debit Note'END debit_note_status,notes.last_number debit_note_number,notes.last_date debit_note_date,a.remarks
 FROM delayed_payment_accounts a JOIN finance_receivable_invoices r ON r.id=a.receivable_id JOIN buyers b ON b.id=a.buyer_id JOIN finance_receivables_view v ON v.id=r.id CROSS JOIN delayed_payment_settings s
 LEFT JOIN LATERAL(SELECT * FROM delayed_payment_accruals x WHERE x.account_id=a.id ORDER BY accrual_date DESC LIMIT 1)last ON true
 LEFT JOIN LATERAL(SELECT COALESCE(sum(amount)FILTER(WHERE status='Approved'),0)approved,count(*)FILTER(WHERE status IN('Debit Note Draft','Pending Final Approval'))pending,max(debit_note_number)FILTER(WHERE status='Approved')last_number,max(debit_note_date)FILTER(WHERE status='Approved')last_date FROM delayed_payment_debit_notes n WHERE n.account_id=a.id)notes ON true
 LEFT JOIN LATERAL(SELECT max(p.payment_date)last_payment_date FROM finance_receipt_allocations ra JOIN finance_customer_payments p ON p.id=ra.payment_id WHERE ra.receivable_id=r.id)pay ON true`;
async function audit(c,account,event,oldV,newV,user,note=null){await c.query("INSERT INTO delayed_payment_audit(account_id,debit_note_id,event_type,old_values,new_values,user_id)VALUES($1,$2,$3,$4,$5,$6)",[account,note,event,oldV,newV,user])}
export const DelayedPaymentsService={
 async settings(){return safeJson((await query("SELECT * FROM delayed_payment_settings WHERE id=1")).rows[0])},
 async updateSettings(p,user){const allowed=["daily_rate_percent","grace_period_days","calculation_base","partial_payment_treatment","tax_treatment","debit_note_prefix","due_soon_days","significant_delay_days"],f=allowed.filter(k=>p[k]!==undefined),v=f.map(k=>p[k]);if(!f.length)return this.settings();v.push(user);return safeJson((await query(`UPDATE delayed_payment_settings SET ${f.map((k,i)=>`${k}=$${i+1}`).join(",")},updated_by=$${v.length},updated_at=now()WHERE id=1 RETURNING *`,v)).rows[0])},
 async syncAccounts(){const s=await this.settings();const result=await query(`INSERT INTO delayed_payment_accounts(receivable_id,buyer_id,order_id,buyer_gst,invoice_value,gst_amount,value_excluding_gst,delivery_date,payment_terms,credit_days,due_date,grace_period_days,first_chargeable_date)
 SELECT r.id,r.buyer_id,o.id,(SELECT gst_number FROM buyer_locations WHERE buyer_id=r.buyer_id ORDER BY id LIMIT 1),r.invoice_value,0,r.invoice_value,o.delivery_date,COALESCE(r.payment_terms,b.payment_terms),COALESCE(NULLIF(r.credit_days,0),(regexp_match(COALESCE(b.payment_terms,''),'([0-9]+)'))[1]::int,0),o.delivery_date+COALESCE(NULLIF(r.credit_days,0),(regexp_match(COALESCE(b.payment_terms,''),'([0-9]+)'))[1]::int,0),$1::int,o.delivery_date+COALESCE(NULLIF(r.credit_days,0),(regexp_match(COALESCE(b.payment_terms,''),'([0-9]+)'))[1]::int,0)+$1::int+1
 FROM finance_receivable_invoices r JOIN finance_commercial_records c ON c.id=r.commercial_id JOIN orders o ON o.id=c.order_id JOIN buyers b ON b.id=r.buyer_id WHERE o.delivery_date IS NOT NULL ON CONFLICT(receivable_id)DO NOTHING RETURNING id`,[s.grace_period_days]);return result.rowCount},
 async accrue(targetDate=new Date().toISOString().slice(0,10)){await this.syncAccounts();const c=await getClient();let inserted=0;try{await c.query("BEGIN");const s=(await c.query("SELECT * FROM delayed_payment_settings WHERE id=1")).rows[0],accounts=(await c.query("SELECT * FROM delayed_payment_accounts WHERE first_chargeable_date<=$1 ORDER BY id",[targetDate])).rows;for(const a of accounts){const start=(await c.query("SELECT COALESCE(max(accrual_date)+1,$2::date) d FROM delayed_payment_accruals WHERE account_id=$1",[a.id,a.first_chargeable_date])).rows[0].d;const days=(await c.query("SELECT d::date accrual_date FROM generate_series($1::date,$2::date,interval'1 day')d",[start,targetDate])).rows;for(const {accrual_date}of days){const paid=+(await c.query("SELECT COALESCE(sum(ra.allocated_amount),0) amount FROM finance_receipt_allocations ra JOIN finance_customer_payments p ON p.id=ra.payment_id WHERE ra.receivable_id=$1 AND p.payment_date<=$2",[a.receivable_id,accrual_date])).rows[0].amount,principal=Math.max(+a.value_excluding_gst-paid,0);if(principal<=0){await c.query("UPDATE delayed_payment_accounts SET payment_status='Settled',settled_at=COALESCE(settled_at,$2),updated_at=now()WHERE id=$1",[a.id,accrual_date]);break}const previous=+(await c.query("SELECT COALESCE(sum(daily_charge),0)n FROM delayed_payment_accruals WHERE account_id=$1",[a.id])).rows[0].n,charge=Number((principal*(+s.daily_rate_percent/100)).toFixed(2)),day=Math.floor((new Date(accrual_date)-new Date(a.due_date))/86400000)-a.grace_period_days;const row=(await c.query("INSERT INTO delayed_payment_accruals(account_id,accrual_date,overdue_day_number,applicable_principal,daily_rate_percent,daily_charge,cumulative_accrued,payment_adjustment,calculation_base)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)ON CONFLICT(account_id,accrual_date)DO NOTHING RETURNING *",[a.id,accrual_date,day,principal,s.daily_rate_percent,charge,previous+charge,paid,s.calculation_base])).rows[0];if(row){inserted++;await audit(c,a.id,"Daily Accrual",null,row,null)}}}await c.query("COMMIT");return{inserted,target_date:targetDate}}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}},
 async register(p={}){await this.accrue();const v=[],w=[];if(p.search){v.push(`%${p.search}%`);w.push(`concat_ws(' ',buyer,buyer_gst,invoice_number,debit_note_number)ILIKE $${v.length}`)}if(p.status){v.push(p.status);w.push(`debit_note_status=$${v.length}`)}const r=await query(`SELECT * FROM(${registerSql})x ${w.length?`WHERE ${w.join(" AND ")}`:""} ORDER BY due_date,invoice_number`,v);return r.rows.map(safeJson)},
 async history(accountId){return(await query("SELECT * FROM delayed_payment_accruals WHERE account_id=$1 ORDER BY accrual_date DESC",[accountId])).rows.map(safeJson)},
 async generateDebitNote(accountId,user){await this.accrue();const c=await getClient();try{await c.query("BEGIN");const x=(await c.query(`SELECT a.*,r.invoice_number,r.invoice_date,b.group_name buyer,COALESCE((SELECT sum(daily_charge)FROM delayed_payment_accruals WHERE account_id=a.id),0)-COALESCE((SELECT sum(amount)FROM delayed_payment_debit_notes WHERE account_id=a.id AND status='Approved'),0) unbilled FROM delayed_payment_accounts a JOIN finance_receivable_invoices r ON r.id=a.receivable_id JOIN buyers b ON b.id=a.buyer_id WHERE a.id=$1 FOR UPDATE`,[accountId])).rows[0];if(!x)throw bad("Delayed-payment account not found.",404);if(+x.unbilled<=0)throw bad("No unbilled delayed-payment charge is available.",409);const note=(await c.query("INSERT INTO delayed_payment_debit_notes(account_id,amount,status,generated_by)VALUES($1,$2,'Pending Final Approval',$3)RETURNING *",[accountId,x.unbilled,user])).rows[0];await audit(c,accountId,"Debit Note Generated",null,note,user,note.id);await c.query("COMMIT");await NotificationsService.notifyAdmins("Debit note approval pending",`${note.system_reference} for ₹${note.amount} requires final approval.`,"warning","/finance");return safeJson(note)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}},
 async notes(p={}){const values=[],where=[];if(p.status){values.push(p.status);where.push(`n.status=$${values.length}`)}return(await query(`SELECT n.*,b.group_name buyer,r.invoice_number,r.invoice_date,a.delivery_date,a.due_date,a.payment_terms,a.buyer_gst,g.name generated_by_name,ap.name approved_by_name FROM delayed_payment_debit_notes n JOIN delayed_payment_accounts a ON a.id=n.account_id JOIN finance_receivable_invoices r ON r.id=a.receivable_id JOIN buyers b ON b.id=a.buyer_id LEFT JOIN users g ON g.id=n.generated_by LEFT JOIN users ap ON ap.id=n.approved_by ${where.length?`WHERE ${where.join(" AND ")}`:""} ORDER BY n.generated_at DESC`,values)).rows.map(safeJson)},
 async decide(id,p,user){if(!["Approved","Rejected"].includes(p.status))throw bad("Decision must be Approved or Rejected.");const c=await getClient();try{await c.query("BEGIN");const n=(await c.query("SELECT n.*,a.*,r.invoice_number,r.invoice_date,b.group_name buyer FROM delayed_payment_debit_notes n JOIN delayed_payment_accounts a ON a.id=n.account_id JOIN finance_receivable_invoices r ON r.id=a.receivable_id JOIN buyers b ON b.id=a.buyer_id WHERE n.id=$1 FOR UPDATE",[id])).rows[0];if(!n)throw bad("Debit note not found.",404);if(n.status!=="Pending Final Approval")throw bad("Only a pending debit note can be decided.",409);if(p.status==="Rejected"){const row=(await c.query("UPDATE delayed_payment_debit_notes SET status='Rejected',approved_by=$2,approval_date=now(),rejection_reason=$3,approval_remarks=$4,updated_at=now()WHERE id=$1 RETURNING *",[id,user,p.reason,p.remarks])).rows[0];await audit(c,n.account_id,"Debit Note Rejected",n,row,user,id);await c.query("COMMIT");return safeJson(row)}const s=(await c.query("SELECT * FROM delayed_payment_settings WHERE id=1")).rows[0],number=`${s.debit_note_prefix}-${new Date().getFullYear()}-${String(id).padStart(6,"0")}`,html=`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial;padding:40px;color:#123}table{width:100%;border-collapse:collapse}td{border:1px solid #bbb;padding:8px}</style></head><body><h1>Debit Note</h1><h2>${number}</h2><table><tr><td>Buyer</td><td>${n.buyer}</td></tr><tr><td>Buyer GST</td><td>${n.buyer_gst||""}</td></tr><tr><td>Original Invoice</td><td>${n.invoice_number} (${n.invoice_date})</td></tr><tr><td>Delivery / Due Date</td><td>${n.delivery_date} / ${n.due_date}</td></tr><tr><td>Payment Terms</td><td>${n.payment_terms||""}</td></tr><tr><td>Delayed Payment Rate</td><td>${s.daily_rate_percent}% per day</td></tr><tr><td>Calculation Base</td><td>${s.calculation_base}</td></tr><tr><td>Delayed Payment Amount</td><td>₹${n.amount}</td></tr><tr><td>Tax Treatment</td><td>${s.tax_treatment}</td></tr></table><p>Reason: Delayed payment charges against overdue invoice.</p></body></html>`;const row=(await c.query("UPDATE delayed_payment_debit_notes SET status='Approved',debit_note_number=$2,debit_note_date=CURRENT_DATE,approved_by=$3,approval_date=now(),approval_remarks=$4,document_html=$5,updated_at=now()WHERE id=$1 RETURNING *",[id,number,user,p.remarks,html])).rows[0];await audit(c,n.account_id,"Debit Note Approved",n,row,user,id);await c.query("COMMIT");return safeJson(row)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}},
 async document(id){const n=(await query("SELECT debit_note_number,system_reference,document_html FROM delayed_payment_debit_notes WHERE id=$1 AND status='Approved'",[id])).rows[0];if(!n)throw bad("Approved debit-note document not found.",404);return{filename:`${n.debit_note_number||n.system_reference}.html`,html:n.document_html}},
 async dashboard(){return safeJson((await query(`SELECT COALESCE(sum(current_outstanding)FILTER(WHERE overdue_days>0),0)total_overdue_principal,COALESCE(sum(total_accrued_charge),0)total_accrued_charges,COALESCE(sum(unbilled_accrued_charge),0)current_unbilled_charges,count(*)FILTER(WHERE debit_note_number IS NOT NULL)debit_notes_generated,count(*)FILTER(WHERE debit_note_status='Pending Final Approval')debit_notes_pending_approval,count(*)FILTER(WHERE debit_note_status='Approved')debit_notes_approved,count(DISTINCT buyer_id)FILTER(WHERE overdue_days>0)overdue_buyers,count(*)FILTER(WHERE overdue_days>0)overdue_invoices FROM(${registerSql})x`)).rows[0])},
 async buyerBehaviour(id){return safeJson((await query(`SELECT COALESCE(sum(invoice_value),0)total_credit_sales,COALESCE(sum(current_outstanding),0)total_outstanding,COALESCE(sum(current_outstanding)FILTER(WHERE overdue_days>0),0)current_overdue_amount,COALESCE(avg(overdue_days)FILTER(WHERE payment_status='Settled'),0)average_payment_delay,COALESCE(max(overdue_days),0)maximum_payment_delay,count(*)FILTER(WHERE overdue_days>0)overdue_invoices,COALESCE(sum(total_accrued_charge),0)total_delayed_payment_charges,count(*)FILTER(WHERE debit_note_number IS NOT NULL)total_debit_notes,count(*)FILTER(WHERE debit_note_status='Pending Final Approval')pending_debit_notes,GREATEST(0,100-LEAST(100,COALESCE(avg(overdue_days),0)*2))payment_behaviour_score FROM(${registerSql})x WHERE buyer_id=$1`,[id])).rows[0])}
};
