import{query}from"../db.js";import{safeJson,sendMail}from"../utils.js";import{NotificationsService}from"./notifications.service.js";
const fallback={user_login:{email_enabled:true,in_app_enabled:true,recipient_mode:"Admins"},user_created:{email_enabled:true,in_app_enabled:true,recipient_mode:"Admins"},email_verification:{email_enabled:true,in_app_enabled:false,recipient_mode:"Actor"},password_reset:{email_enabled:true,in_app_enabled:false,recipient_mode:"Actor"},monthly_business_report:{email_enabled:true,in_app_enabled:true,recipient_mode:"Admins"},scheduled_bi_report:{email_enabled:true,in_app_enabled:false,recipient_mode:"Custom"}};
export const EmailNotificationsService={
 async rules(){return(await query("SELECT * FROM settings_email_notification_rules ORDER BY category,event_name")).rows.map(safeJson)},
 async rule(key){try{return(await query("SELECT * FROM settings_email_notification_rules WHERE event_key=$1",[key])).rows[0]||fallback[key]||{email_enabled:false,in_app_enabled:true,recipient_mode:"Admins"}}catch(e){if(e.code!=="42P01")throw e;return fallback[key]||{email_enabled:false,in_app_enabled:true,recipient_mode:"Admins"}}},
 async update(key,p,user){const custom=Array.isArray(p.custom_recipients)?p.custom_recipients.map(x=>String(x).trim()).filter(Boolean):[],r=await query("UPDATE settings_email_notification_rules SET email_enabled=$1,in_app_enabled=$2,recipient_mode=$3,custom_recipients=$4,updated_by=$5,updated_at=now()WHERE event_key=$6 RETURNING *",[p.email_enabled===true,p.in_app_enabled===true,p.recipient_mode||"Admins",JSON.stringify(custom),user,key]);if(!r.rowCount)throw Object.assign(new Error("Email notification event not found."),{status:404});return safeJson(r.rows[0])},
 async recipients(rule,actor,override){if(Array.isArray(override)&&override.length)return override;if(rule.recipient_mode==="Actor")return actor?[actor]:[];if(rule.recipient_mode==="Custom")return Array.isArray(rule.custom_recipients)?rule.custom_recipients:[];return(await NotificationsService.admins()).map(x=>x.email)},
 async dispatch(key,o={}){const rule=await this.rule(key),title=o.title||o.subject,message=o.message||title;if(rule.in_app_enabled)await NotificationsService.notifyAdmins(title,message,o.type||"info",o.link||"/dashboard",{event_key:key,email_dispatched:true});if(!rule.email_enabled)return{emailed:0,notified:!!rule.in_app_enabled};const targets=[...new Set((await this.recipients(rule,o.actorEmail,o.recipients)).filter(Boolean))],results=await Promise.allSettled(targets.map(to=>sendMail(to,o.subject||`Cresco CRM: ${title}`,o.html||`<p>${message}</p>`,o.attachments?{attachments:o.attachments}:{})));return{emailed:results.filter(x=>x.status==="fulfilled").length,notified:!!rule.in_app_enabled}}
};
