import ExcelJS from "exceljs";
import { getClient,query } from "../db.js";
const HEADERS=["FROM","TO","LOAD","FREIGHT"];
const clean=v=>String(v??"").trim();
function csvRows(text){const out=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===","&&!quoted){row.push(cell);cell=""}else if((ch==="\n"||ch==="\r")&&!quoted){if(ch==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(x=>clean(x)))out.push(row);row=[];cell=""}else cell+=ch}row.push(cell);if(row.some(x=>clean(x)))out.push(row);return out}
async function readFile(file){if(!file)throw Object.assign(new Error("Select a freight CSV or Excel file."),{status:400});let matrix;if(file.originalname.toLowerCase().endsWith(".csv"))matrix=csvRows(file.buffer.toString("utf8"));else{const wb=new ExcelJS.Workbook();await wb.xlsx.load(file.buffer);const ws=wb.worksheets[0];if(!ws)throw Object.assign(new Error("Uploaded workbook has no worksheet."),{status:400});matrix=[];ws.eachRow(r=>matrix.push(r.values.slice(1)))}if(!matrix.length)throw Object.assign(new Error("Uploaded file is empty."),{status:400});const headers=matrix[0].map(x=>clean(x).toUpperCase()),missing=HEADERS.filter(x=>!headers.includes(x));if(missing.length)throw Object.assign(new Error(`Invalid freight file. Missing headings: ${missing.join(", ")}`),{status:400});return matrix.slice(1).filter(r=>r.some(x=>clean(x))).map((r,index)=>({row:index+2,from:clean(r[headers.indexOf("FROM")]).toUpperCase(),to:clean(r[headers.indexOf("TO")]).toUpperCase(),load:+clean(r[headers.indexOf("LOAD")]).replaceAll(",",""),freight:+clean(r[headers.indexOf("FREIGHT")]).replace(/[₹,]/g,"")}))}
function validate(rows){const seen=new Set(),issues=[];for(const r of rows){let error="";if(!r.from)error="FROM district is blank";else if(!r.to)error="TO district is blank";else if(!Number.isFinite(r.load)||r.load<=0)error="LOAD must be a positive quantity in KG";else if(!Number.isFinite(r.freight)||r.freight<0)error="FREIGHT must be a non-negative Rs/Kg value";const key=`${r.from}|${r.to}|${r.load}`;if(!error&&seen.has(key))error="Duplicate From + To + Load in uploaded file";seen.add(key);if(error)issues.push({...r,error})}return issues}
async function invalidReport(issues){const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet("Invalid Freight Rows");ws.columns=[{header:"Source Row",key:"row",width:12},{header:"FROM",key:"from",width:24},{header:"TO",key:"to",width:24},{header:"LOAD (KG)",key:"load",width:16},{header:"FREIGHT (Rs/Kg)",key:"freight",width:20},{header:"Error",key:"error",width:48}];ws.addRows(issues);ws.getRow(1).font={bold:true};return Buffer.from(await wb.xlsx.writeBuffer()).toString("base64")}
async function district(client,value,field="district"){
 const raw=clean(value);if(!raw)throw Object.assign(new Error(`Select ${field} from District Master.`),{status:400});
 const byId=/^\d+$/.test(raw)?await client.query("SELECT id,name,state FROM logistics_districts WHERE id=$1 AND is_active",[raw]):{rows:[]};
 if(byId.rows[0])return byId.rows[0];
 const matches=await client.query("SELECT id,name,state FROM logistics_districts WHERE is_active AND (upper(trim(name))=upper(trim($1)) OR upper(code)=upper($1)) ORDER BY state,name,id",[raw]);
 if(matches.rowCount===1)return matches.rows[0];
 if(!matches.rowCount)throw Object.assign(new Error(`${field} '${raw}' is not in District Master.`),{status:400});
 throw Object.assign(new Error(`${field} '${raw}' exists in multiple states. Use its unique District Master code.`),{status:400});
}
async function validateDistrictRows(rows,client=query){
 const issues=[];
 for(const r of rows){
  try{r.fromDistrict=await district({query:client},r.from,"FROM district")}catch(error){issues.push({...r,error:error.message});continue}
  try{r.toDistrict=await district({query:client},r.to,"TO district")}catch(error){issues.push({...r,error:error.message});continue}
  if(r.fromDistrict.id===r.toDistrict.id)issues.push({...r,error:"FROM and TO districts must be different"});
 }
 return issues;
}
export const FreightImportService={
 async rates(filters={}){const values=[],conditions=["b.is_active","f.is_active","t.is_active"];if(clean(filters.from)){values.push(clean(filters.from));conditions.push(/^\d+$/.test(clean(filters.from))?`f.id=$${values.length}`:`f.name ILIKE '%'||$${values.length}||'%'`)}if(clean(filters.to)){values.push(clean(filters.to));conditions.push(/^\d+$/.test(clean(filters.to))?`t.id=$${values.length}`:`t.name ILIKE '%'||$${values.length}||'%'`)}return(await query(`SELECT b.id,b.from_district_id,b.to_district_id,f.name from_district,f.state from_state,t.name to_district,t.state to_state,b.quantity_kg,b.base_freight_per_kg,b.effective_from,b.source,b.source_reference,b.version,b.created_at,u.name created_by_name FROM logistics_base_freight b JOIN logistics_districts f ON f.id=b.from_district_id JOIN logistics_districts t ON t.id=b.to_district_id LEFT JOIN users u ON u.id=b.created_by WHERE ${conditions.join(" AND ")} ORDER BY b.created_at DESC,b.id DESC LIMIT 1000`,values)).rows},
 async saveManual(p,user){const load=+p.load,freight=+p.freight;if(!Number.isFinite(load)||load<=0||!Number.isFinite(freight)||freight<0)throw Object.assign(new Error("Invalid input: enter districts, positive Load KG and non-negative Freight Rs/Kg."),{status:400});const c=await getClient();try{await c.query("BEGIN");const fromDistrict=await district(c,p.from_district_id??p.from,"From district"),toDistrict=await district(c,p.to_district_id??p.to,"To district");if(fromDistrict.id===toDistrict.id)throw Object.assign(new Error("From and To districts must be different."),{status:400});const fromId=fromDistrict.id,toId=toDistrict.id,old=(await c.query("SELECT * FROM logistics_base_freight WHERE from_district_id=$1 AND to_district_id=$2 AND quantity_kg=$3 AND is_active ORDER BY version DESC LIMIT 1 FOR UPDATE",[fromId,toId,load])).rows[0];if(old)await c.query("UPDATE logistics_base_freight SET is_active=false,effective_to=CURRENT_DATE WHERE id=$1",[old.id]);const row=(await c.query("INSERT INTO logistics_base_freight(from_district_id,to_district_id,quantity_kg,base_freight_per_kg,source,source_reference,version,created_by)VALUES($1,$2,$3,$4,'Manual',$5,$6,$7)RETURNING *",[fromId,toId,load,freight,p.remarks||null,(old?.version||0)+1,user])).rows[0];await c.query("INSERT INTO logistics_audit_history(record,field,old_value,new_value,user_id,reason,source)VALUES($1,'base_freight_per_kg',$2,$3,$4,$5,'Manual')",[row.id,JSON.stringify(old?.base_freight_per_kg??null),JSON.stringify(freight),user,p.remarks||"Manual base freight entry"]);await c.query("COMMIT");return row}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}},
 async analyze(file){const rows=await readFile(file),rawIssues=validate(rows),structurallyBad=new Set(rawIssues.map(x=>x.row)),districtIssues=await validateDistrictRows(rows.filter(x=>!structurallyBad.has(x.row))),issues=[...rawIssues,...districtIssues],bad=new Set(issues.map(x=>x.row)),valid=rows.filter(x=>!bad.has(x.row));let existing=0;for(const r of valid){const q=await query("SELECT 1 FROM logistics_base_freight WHERE from_district_id=$1 AND to_district_id=$2 AND quantity_kg=$3 AND is_active",[r.fromDistrict.id,r.toDistrict.id,r.load]);if(q.rowCount)existing++}return{totalRows:rows.length,validRows:valid.length,invalidRows:bad.size,newRows:valid.length-existing,updates:existing,issues,invalidReport:issues.length?await invalidReport(issues):null,unit:"Rs/Kg",loadUnit:"KG"}},
 async import(file,user){const rows=await readFile(file),issues=[...validate(rows),...await validateDistrictRows(rows)];if(issues.length)throw Object.assign(new Error("Import stopped. Every district must match one active District Master record; correct the invalid rows shown in analysis."),{status:400,issues});const c=await getClient();try{await c.query("BEGIN");const imp=(await c.query("INSERT INTO logistics_freight_imports(filename,file_type,status,total_rows,valid_rows,uploaded_by)VALUES($1,$2,'Processing',$3,$3,$4)RETURNING id",[file.originalname,file.originalname.toLowerCase().endsWith(".csv")?"CSV":"XLSX",rows.length,user])).rows[0];let inserted=0,updated=0;for(const r of rows){const from=(await district(c,r.from,"FROM district")).id,to=(await district(c,r.to,"TO district")).id;const old=(await c.query("SELECT * FROM logistics_base_freight WHERE from_district_id=$1 AND to_district_id=$2 AND quantity_kg=$3 AND is_active ORDER BY version DESC LIMIT 1 FOR UPDATE",[from,to,r.load])).rows[0];if(old&&+old.base_freight_per_kg===r.freight)continue;if(old){await c.query("UPDATE logistics_base_freight SET is_active=false,effective_to=CURRENT_DATE WHERE id=$1",[old.id]);updated++}else inserted++;const version=(old?.version||0)+1,newRow=(await c.query("INSERT INTO logistics_base_freight(from_district_id,to_district_id,quantity_kg,base_freight_per_kg,source,source_reference,version,created_by,import_id)VALUES($1,$2,$3,$4,'Excel Import',$5,$6,$7,$8)RETURNING *",[from,to,r.load,r.freight,file.originalname,version,user,imp.id])).rows[0];await c.query("INSERT INTO logistics_audit_history(record,field,old_value,new_value,user_id,reason,source) VALUES($1,$2,$3,$4,$5,$6,$7)",[newRow.id,"base_freight_per_kg",old?.base_freight_per_kg??null,r.freight,user,"Freight bulk import",file.originalname]).catch(()=>c.query("INSERT INTO logistics_audit_history(record_type,record_id,field_name,old_value,new_value,changed_by,reason,source)VALUES('base_freight',$1,'base_freight_per_kg',$2,$3,$4,'Freight bulk import',$5)",[newRow.id,JSON.stringify(old?.base_freight_per_kg??null),JSON.stringify(r.freight),user,file.originalname]))}await c.query("UPDATE logistics_freight_imports SET status='Completed',inserted_rows=$1,updated_rows=$2,completed_at=now() WHERE id=$3",[inserted,updated,imp.id]);await c.query("COMMIT");return{rows:rows.length,inserted,updated,unchanged:rows.length-inserted-updated,importId:imp.id}}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}},
 async history(){return(await query("SELECT i.*,u.name uploaded_by_name FROM logistics_freight_imports i LEFT JOIN users u ON u.id=i.uploaded_by ORDER BY created_at DESC LIMIT 100")).rows},
 async template(){const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet("Base Freight Upload"),districtSheet=wb.addWorksheet("District Master");ws.columns=[{header:"FROM",key:"from",width:34},{header:"TO",key:"to",width:34},{header:"LOAD",key:"load",width:14},{header:"FREIGHT",key:"freight",width:18}];ws.addRow({from:"DIST-AHMEDABAD-GUJARAT",to:"DIST-INDORE-MADHYA-P",load:5000,freight:1.25});ws.getRow(1).font={bold:true};ws.getCell("F1").value="FROM/TO: use the District Master code (recommended) or an exact unique district name";ws.getCell("F2").value="LOAD unit: KG";ws.getCell("F3").value="FREIGHT unit: Rs/Kg";districtSheet.columns=[{header:"DISTRICT CODE",key:"code",width:36},{header:"DISTRICT",key:"name",width:28},{header:"STATE / UNION TERRITORY",key:"state",width:42}];districtSheet.addRows((await query("SELECT code,name,state FROM logistics_districts WHERE is_active ORDER BY state,name")).rows);districtSheet.getRow(1).font={bold:true};districtSheet.views=[{state:"frozen",ySplit:1}];districtSheet.autoFilter={from:"A1",to:"C1"};return wb.xlsx.writeBuffer()}
};
