import { query } from "../db.js";
const bad=message=>{throw Object.assign(new Error(message),{status:400})};
export const LogisticsMasterService={
 async districts(){return(await query("SELECT d.id,d.name,d.state,d.state_code,d.code,d.is_active,COALESCE(array_agg(p.pincode ORDER BY p.pincode)FILTER(WHERE p.is_active),'{}') pincodes FROM logistics_districts d LEFT JOIN logistics_district_pincodes p ON p.district_id=d.id GROUP BY d.id ORDER BY d.state,d.name")).rows},
 async saveDistrict(p){const name=String(p.name??"").trim().toUpperCase(),state=String(p.state??"").trim(),stateCode=String(p.state_code??"").trim().toUpperCase()||null,pincodes=[...new Set(String(p.pincodes??"").split(",").map(x=>x.trim()).filter(Boolean))];if(!name||!state)bad("District name and state are required.");if(pincodes.some(x=>!/^\d{6}$/.test(x)))bad("Every pincode must contain exactly 6 digits.");const c=await query("INSERT INTO logistics_districts(name,state,state_code,code)VALUES($1,$2,$3,$4)ON CONFLICT(name,state)DO UPDATE SET state_code=EXCLUDED.state_code,is_active=true,updated_at=now() RETURNING *",[name,state,stateCode,`DIST-${name.replace(/[^A-Z0-9]+/g,"-").slice(0,20)}-${(stateCode||state).replace(/[^A-Z0-9]+/gi,"-").toUpperCase().slice(0,8)}`]);for(const pincode of pincodes)await query("INSERT INTO logistics_district_pincodes(district_id,pincode)VALUES($1,$2)ON CONFLICT(district_id,pincode)DO UPDATE SET is_active=true",[c.rows[0].id,pincode]);return c.rows[0]},
 async pincode(value){const p=String(value??"").trim();if(!/^\d{6}$/.test(p))bad("Invalid input: pincode must contain 6 digits.");const [districts,warehouses]=await Promise.all([query("SELECT d.id,d.name district,d.state,d.state_code FROM logistics_district_pincodes p JOIN logistics_districts d ON d.id=p.district_id WHERE p.pincode=$1 AND p.is_active AND d.is_active ORDER BY d.name",[p]),query("SELECT w.id,w.warehouse_name,w.warehouse_code,w.address,w.district,w.pincode,s.id supplier_id,s.group_name supplier_name FROM supplier_warehouses w JOIN suppliers s ON s.id=w.supplier_id WHERE w.pincode=$1 AND s.is_active ORDER BY s.group_name,w.warehouse_name",[p])]);const names=[...new Set([...districts.rows.map(x=>x.district),...warehouses.rows.map(x=>x.district).filter(Boolean)])];return{pincode:p,district:names.length===1?names[0]:null,districts:districts.rows,warehouses:warehouses.rows}},
 async notes(){return(await query("SELECT * FROM logistics_lane_note_options WHERE is_active ORDER BY sort_order,label")).rows},
 async saveNote(p){const label=String(p.label??"").trim();if(!label)bad("Lane note cannot be blank.");return(await query("INSERT INTO logistics_lane_note_options(label,sort_order)VALUES($1,$2)ON CONFLICT(label)DO UPDATE SET is_active=true,sort_order=EXCLUDED.sort_order RETURNING *",[label,+p.sort_order||0])).rows[0]},
 async removeNote(id){const row=(await query("UPDATE logistics_lane_note_options SET is_active=false WHERE id=$1 RETURNING id",[id])).rows[0];if(!row)throw Object.assign(new Error("Lane note not found."),{status:404});return{message:"Lane note removed."}}
};
