import{query}from"../db.js";import{safeJson,sendMail}from"../utils.js";
const eventKeys={"Sales stage updated":"sales_stage_updated","Customer payment received":"customer_payment_received","Debit note approval pending":"debit_note_approval","Supplier prices expiring":"supplier_prices_expiring","Payments overdue":"payments_overdue","Orders delayed":"orders_delayed","Database housekeeping completed":"database_housekeeping"};
export const NotificationsService={
 async list(userId,p={}){const limit=Math.min(+p.limit||30,100),r=await query("SELECT * FROM notifications WHERE user_id=$1 AND archived_at IS NULL ORDER BY created_at DESC LIMIT $2",[userId,limit]),unread=await query("SELECT count(*) FROM notifications WHERE user_id=$1 AND archived_at IS NULL AND NOT is_read",[userId]);return{data:r.rows.map(safeJson),unread:+unread.rows[0].count}},
 async history(userId,p={}){const limit=Math.min(+p.limit||100,500);return(await query("SELECT * FROM notifications WHERE user_id=$1 AND archived_at IS NOT NULL ORDER BY archived_at DESC LIMIT $2",[userId,limit])).rows.map(safeJson)},
 async clear(userId){const r=await query("UPDATE notifications SET archived_at=now(),is_read=TRUE WHERE user_id=$1 AND archived_at IS NULL",[userId]);return{message:`${r.rowCount} notifications cleared and moved to history.`,count:r.rowCount}},
 async markRead(userId,id){return safeJson((await query("UPDATE notifications SET is_read=TRUE WHERE id=$1 AND user_id=$2 RETURNING *",[id,userId])).rows[0])},
 async markAllRead(userId){await query("UPDATE notifications SET is_read=TRUE WHERE user_id=$1 AND NOT is_read",[userId]);return{message:"All notifications marked read."}},
 async notifyAdmins(title,message,type="info",link=null,metadata={}){let rule,key=metadata.event_key||eventKeys[title];if(key)try{rule=(await query("SELECT * FROM settings_email_notification_rules WHERE event_key=$1",[key])).rows[0]}catch(e){if(e.code!=="42P01")throw e}if(rule?.in_app_enabled!==false)await query("INSERT INTO notifications(user_id,title,message,type,link,metadata) SELECT id,$1,$2,$3,$4,$5 FROM users WHERE is_admin AND is_active",[title,message,type,link,metadata]);if(rule?.email_enabled&&!metadata.email_dispatched){const recipients=rule.recipient_mode==="Custom"?rule.custom_recipients:(await this.admins()).map(x=>x.email);await Promise.allSettled((recipients||[]).map(to=>sendMail(to,`Cresco CRM: ${title}`,`<p>${message}</p>`)))}},
 async admins(){return(await query("SELECT email,name FROM users WHERE is_admin AND is_active AND email_verified")).rows}
};
