import{query}from"../db.js";import{safeJson}from"../utils.js";
const definitions=[
 ["Buyer","buyers","/buyers","SELECT id,group_name title,concat_ws(' · ',state,group_tag,lifecycle_status) subtitle FROM buyers WHERE concat_ws(' ',group_name,pan,state,group_tag,lead_type,lifecycle_status) ILIKE $1 ORDER BY similarity(concat_ws(' ',group_name,pan,state,group_tag),$2) DESC LIMIT $3"],
 ["Supplier","suppliers","/suppliers","SELECT id,group_name title,concat_ws(' · ',country,supplier_tag,email) subtitle FROM suppliers WHERE is_active AND concat_ws(' ',group_name,pan,gst_number,email,country,supplier_tag) ILIKE $1 ORDER BY similarity(concat_ws(' ',group_name,email,supplier_tag),$2) DESC LIMIT $3"],
 ["Order","orders","/orders","SELECT id,order_number title,concat_ws(' · ',product_category,grade,status) subtitle FROM orders WHERE deleted_at IS NULL AND concat_ws(' ',order_number,inquiry_number,product_category,grade,status,invoice_number) ILIKE $1 ORDER BY similarity(order_number,$2) DESC,created_at DESC LIMIT $3"],
 ["Inquiry","inquiries","/orders","SELECT id,inquiry_number title,concat_ws(' · ',inquiry_type,current_stage,status) subtitle FROM sales_transactions WHERE deleted_at IS NULL AND concat_ws(' ',inquiry_number,inquiry_type,inquiry_source,current_stage,status,remarks) ILIKE $1 ORDER BY similarity(inquiry_number,$2) DESC,updated_at DESC LIMIT $3"],
 ["Commercial","finance","/finance","SELECT id,commercial_number title,concat_ws(' · ',buyer_name,order_number,current_stage) subtitle FROM finance_commercial_register_view WHERE concat_ws(' ',commercial_number,order_number,buyer_name,supplier_name,buyer_invoice_number,product_category,grade) ILIKE $1 ORDER BY similarity(commercial_number,$2) DESC,updated_at DESC LIMIT $3"],
 ["Logistics Lane","logistics","/logistics","SELECT id,lane_code title,concat_ws(' → ',pickup_warehouse,delivery_district,delivery_pincode) subtitle FROM logistics_lanes WHERE concat_ws(' ',lane_code,pickup_warehouse,delivery_district,delivery_pincode) ILIKE $1 ORDER BY similarity(lane_code,$2) DESC LIMIT $3"],
 ["User","users","/settings/global-access","SELECT id,name title,email subtitle FROM users WHERE is_active AND concat_ws(' ',name,email) ILIKE $1 ORDER BY similarity(name,$2) DESC LIMIT $3"],
 ["Master Data","settings","/settings/master-data","SELECT r.id,r.name title,concat_ws(' · ',t.name,r.code) subtitle FROM settings_master_records r JOIN settings_master_types t ON t.id=r.master_type_id WHERE r.is_active AND concat_ws(' ',r.code,r.name,r.data::text,t.name) ILIKE $1 ORDER BY similarity(r.name,$2) DESC LIMIT $3"],
 ["Report","reports","/reports","SELECT id,name title,concat_ws(' · ',category,data_source,description) subtitle FROM bi_report_definitions WHERE is_active AND concat_ws(' ',name,category,description,data_source) ILIKE $1 ORDER BY similarity(name,$2) DESC LIMIT $3"]
];
export const SearchService={async search(term,limit=5){const text=String(term||"").trim();if(text.length<2)return[];const per=Math.min(Math.max(+limit||5,1),10),pattern=`%${text.replaceAll("%","\\%").replaceAll("_","\\_")}%`;const settled=await Promise.allSettled(definitions.map(async([type,module,path,sql])=>(await query(sql,[pattern,text,per])).rows.map(row=>safeJson({...row,type,module,path:`${path}${path.includes("?")?"&":"?"}search=${encodeURIComponent(row.title)}`}))));return settled.flatMap(x=>x.status==="fulfilled"?x.value:[]).slice(0,40)}};
