import { query, getClient } from "../db.js";
import { safeJson } from "../utils.js";

const resources = {
  rules: { table: "settings_business_rules", fields: ["code","name","category","description","rule_type","formula","configuration","effective_from","effective_to","priority","is_active"] },
  series: { table: "settings_number_series", fields: ["document_type","prefix","suffix","separator","padding","next_number","reset_frequency","include_financial_year","sample","is_active"] },
  documents: { table: "settings_document_templates", fields: ["template_type","name","subject","body","header_html","footer_html","placeholders","version","is_default","is_active"] },
  communications: { table: "settings_communication_templates", fields: ["channel","template_type","name","subject","body","variables","is_active"] },
  workflows: { table: "settings_approval_workflows", fields: ["code","name","approval_type","trigger_conditions","is_active"] },
  access: { table: "settings_access_permissions", fields: ["role_id","scope_type","scope_key","permissions","conditions"] },
  preferences: { table: "settings_system_preferences", fields: ["section","key","value","data_type","description","is_secret"] }
};
const list = async (sql, values=[]) => (await query(sql, values)).rows.map(safeJson);
async function history(client, kind, id, key, before, after, user, reason) {
  await client.query("INSERT INTO settings_configuration_history(entity_type,entity_id,configuration_key,previous_value,new_value,changed_by,reason)VALUES($1,$2,$3,$4,$5,$6,$7)",[kind,id,key,before,after,user,reason||"Configuration updated"]);
}
export const SettingsService = {
  async overview(){const names=["settings_master_records","settings_business_rules","settings_number_series","settings_document_templates","settings_communication_templates","settings_approval_workflows","settings_access_permissions","settings_system_preferences"];const values=await Promise.all(names.map(x=>query(`SELECT count(*) count FROM ${x}`)));return Object.fromEntries(names.map((x,i)=>[x.replace("settings_","").replace("_records","").replaceAll("_"," "),+values[i].rows[0].count]))},
  async masterTypes(){return list("SELECT t.*,count(r.id)::int record_count FROM settings_master_types t LEFT JOIN settings_master_records r ON r.master_type_id=t.id GROUP BY t.id ORDER BY t.category,t.name")},
  async masterRecords(type){return list("SELECT r.*,t.code master_code,t.name master_name FROM settings_master_records r JOIN settings_master_types t ON t.id=r.master_type_id WHERE t.code=$1 ORDER BY r.sort_order,r.name",[type])},
  async saveMaster(type,id,p,user){const c=await getClient();try{await c.query("BEGIN");const t=(await c.query("SELECT id FROM settings_master_types WHERE code=$1",[type])).rows[0];if(!t)throw new Error("Unknown master type.");let old=null,row;if(id){old=(await c.query("SELECT * FROM settings_master_records WHERE id=$1",[id])).rows[0];row=(await c.query("UPDATE settings_master_records SET code=$1,name=$2,parent_id=$3,data=$4,sort_order=$5,is_active=$6,updated_by=$7,updated_at=now() WHERE id=$8 RETURNING *",[p.code,p.name,p.parent_id||null,p.data||{},p.sort_order||0,p.is_active!==false,user,id])).rows[0]}else row=(await c.query("INSERT INTO settings_master_records(master_type_id,code,name,parent_id,data,sort_order,is_active,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8)RETURNING *",[t.id,p.code,p.name,p.parent_id||null,p.data||{},p.sort_order||0,p.is_active!==false,user])).rows[0];await history(c,"master_record",row.id,type,old,row,user,p.reason);await c.query("COMMIT");return safeJson(row)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}},
  async removeMaster(id,user,reason){const c=await getClient();try{await c.query("BEGIN");const old=(await c.query("SELECT * FROM settings_master_records WHERE id=$1",[id])).rows[0];await c.query("UPDATE settings_master_records SET is_active=false,updated_by=$1,updated_at=now()WHERE id=$2",[user,id]);await history(c,"master_record",id,null,old,{...old,is_active:false},user,reason);await c.query("COMMIT");return{message:"Master record deactivated."}}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}},
  async resource(name){const x=resources[name];if(!x)throw new Error("Unknown settings resource.");if(name==="workflows")return list("SELECT w.*,COALESCE(json_agg(json_build_object('id',l.id,'level_number',l.level_number,'role_id',l.role_id,'role_name',r.name,'min_approvals',l.min_approvals,'can_reject',l.can_reject,'escalation_hours',l.escalation_hours) ORDER BY l.level_number)FILTER(WHERE l.id IS NOT NULL),'[]') levels FROM settings_approval_workflows w LEFT JOIN settings_approval_levels l ON l.workflow_id=w.id LEFT JOIN roles r ON r.id=l.role_id GROUP BY w.id ORDER BY w.name");return list(`SELECT * FROM ${x.table} ORDER BY id DESC`)},
  async saveResource(name,id,p,user){const x=resources[name];if(!x)throw new Error("Unknown settings resource.");const c=await getClient();try{await c.query("BEGIN");const old=id?(await c.query(`SELECT * FROM ${x.table} WHERE id=$1`,[id])).rows[0]:null;const fields=x.fields.filter(f=>p[f]!==undefined);let row;if(id){const values=fields.map(f=>p[f]);values.push(user,id);row=(await c.query(`UPDATE ${x.table} SET ${fields.map((f,i)=>`${f}=$${i+1}`).join(",")}${fields.length?",":""}updated_by=$${values.length-1},updated_at=now() WHERE id=$${values.length} RETURNING *`,values)).rows[0]}else{const values=fields.map(f=>p[f]);values.push(user);const hasCreated=["rules","documents","communications","workflows"].includes(name);row=(await c.query(`INSERT INTO ${x.table}(${fields.join(",")}${fields.length?",":""}${hasCreated?"created_by,":""}updated_by)VALUES(${fields.map((_,i)=>`$${i+1}`).join(",")}${fields.length?",":""}${hasCreated?`$${values.length},`:""}$${values.length})RETURNING *`,values)).rows[0]}if(name==="workflows"&&Array.isArray(p.levels)){await c.query("DELETE FROM settings_approval_levels WHERE workflow_id=$1",[row.id]);for(const l of p.levels)await c.query("INSERT INTO settings_approval_levels(workflow_id,level_number,role_id,min_approvals,can_reject,escalation_hours)VALUES($1,$2,$3,$4,$5,$6)",[row.id,l.level_number,l.role_id,l.min_approvals||1,l.can_reject!==false,l.escalation_hours||null])}await history(c,name,row.id,p.code||p.key||p.name,old,row,user,p.reason);await c.query("COMMIT");return safeJson(row)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}},
  async history(){return list("SELECT h.*,u.name changed_by_name FROM settings_configuration_history h LEFT JOIN users u ON u.id=h.changed_by ORDER BY changed_at DESC LIMIT 1000")}
};
