import { query } from "../db.js";
import { safeJson } from "../utils.js";
const SUPPLIER_FIELDS=["group_name","pan","gst_number","primary_contact_name","primary_contact_number","email","country","registered_address","supplier_tag","remarks","is_active"];
const activity=(supplierId,type,description,userId,metadata={})=>query("INSERT INTO supplier_activities(supplier_id,activity_type,description,created_by,metadata) VALUES($1,$2,$3,$4,$5)",[supplierId,type,description,userId,metadata]);
export const SuppliersService={
 async list(p){const vals=[],where=[];if(p.search){vals.push(`%${p.search}%`);where.push(`concat_ws(' ',s.group_name,s.pan,s.gst_number,s.primary_contact_name,s.supplier_tag) ILIKE $1`)}const allowed=new Set(["group_name","pan","gst_number","primary_contact_name","primary_contact_number","email","country","supplier_tag","is_active","warehouse_count","created_at"]);const sort=allowed.has(p.sort)?p.sort:"created_at",dir=p.direction==="asc"?"ASC":"DESC",page=Math.max(+p.page||1,1),limit=Math.min(Math.max(+p.limit||50,1),200);vals.push(limit,(page-1)*limit);const r=await query(`SELECT s.*,count(DISTINCT w.id)::int warehouse_count,count(*) OVER() total_count FROM suppliers s LEFT JOIN supplier_warehouses w ON w.supplier_id=s.id ${where.length?`WHERE ${where.join(" AND ")}`:""} GROUP BY s.id ORDER BY ${sort} ${dir} LIMIT $${vals.length-1} OFFSET $${vals.length}`,vals);return {data:r.rows.map(safeJson),total:+(r.rows[0]?.total_count||0),page,limit}},
 async get(id){const s=(await query("SELECT * FROM suppliers WHERE id=$1",[id])).rows[0];if(!s)return null;const [contacts,warehouses,documents,activities]=await Promise.all([query("SELECT * FROM supplier_contacts WHERE supplier_id=$1 ORDER BY is_primary DESC,id",[id]),query(`SELECT w.*,COALESCE(json_agg(DISTINCT jsonb_build_object('id',c.id,'name',c.name)) FILTER(WHERE c.id IS NOT NULL),'[]') categories FROM supplier_warehouses w LEFT JOIN supplier_product_categories c ON c.warehouse_id=w.id WHERE w.supplier_id=$1 GROUP BY w.id ORDER BY w.id`,[id]),query("SELECT * FROM supplier_documents WHERE supplier_id=$1 ORDER BY created_at DESC",[id]),query("SELECT a.*,u.name updated_by_name FROM supplier_activities a LEFT JOIN users u ON u.id=a.created_by WHERE supplier_id=$1 ORDER BY occurred_at DESC LIMIT 200",[id])]);return safeJson({...s,contacts:contacts.rows,warehouses:warehouses.rows,documents:documents.rows,activities:activities.rows})},
 async create(p,u){const f=SUPPLIER_FIELDS.filter(k=>p[k]!==undefined),v=f.map(k=>p[k]);const s=(await query(`INSERT INTO suppliers(${f.join(",")}) VALUES(${v.map((_,i)=>`$${i+1}`).join(",")}) RETURNING *`,v)).rows[0];await activity(s.id,"supplier_created","Supplier group created",u);return this.get(s.id)},
 async update(id,p,u){const f=SUPPLIER_FIELDS.filter(k=>p[k]!==undefined),v=f.map(k=>p[k]);if(f.length){v.push(id);await query(`UPDATE suppliers SET ${f.map((k,i)=>`${k}=$${i+1}`).join(",")},updated_at=now() WHERE id=$${v.length}`,v);await activity(id,"supplier_updated","Supplier overview updated",u)}return this.get(id)},
 async remove(id){await query("DELETE FROM suppliers WHERE id=$1",[id]);return {message:"Supplier removed."}},
 async addContact(id,p,u){const r=(await query("INSERT INTO supplier_contacts(supplier_id,name,department,designation,mobile_number,email_address,whatsapp_number,notes,is_primary) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *",[id,p.name,p.department,p.designation,p.mobile_number,p.email_address,p.whatsapp_number,p.notes,p.is_primary??false])).rows[0];await activity(id,"contact_updated",`Contact ${p.name} added`,u);return safeJson(r)},
 async addWarehouse(id,p,u){const r=(await query("INSERT INTO supplier_warehouses(supplier_id,warehouse_name,address,primary_contact,contact_details,dispatch_location,payment_terms,credit_days) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",[id,p.warehouse_name,p.address,p.primary_contact,p.contact_details,p.dispatch_location,p.payment_terms,p.credit_days])).rows[0];await activity(id,"warehouse_added",`Warehouse ${p.warehouse_name} added`,u);return safeJson(r)},
 async catalogue(warehouseId){return (await query(`SELECT c.id category_id,c.name category_name,g.id grade_id,g.name grade_name,p.id price_id,p.purchase_price,p.remarks,p.effective_at,p.expires_at,(p.is_active AND p.expires_at>now()) price_active FROM supplier_product_categories c LEFT JOIN supplier_grades g ON g.category_id=c.id LEFT JOIN LATERAL(SELECT * FROM supplier_grade_prices x WHERE x.grade_id=g.id ORDER BY x.created_at DESC LIMIT 1)p ON true WHERE c.warehouse_id=$1 ORDER BY c.name,g.name`,[warehouseId])).rows.map(safeJson)},
 async addCategory(warehouseId,p,u){const w=(await query("SELECT supplier_id FROM supplier_warehouses WHERE id=$1",[warehouseId])).rows[0];const r=(await query("INSERT INTO supplier_product_categories(warehouse_id,name) VALUES($1,$2) RETURNING *",[warehouseId,p.name])).rows[0];await activity(w.supplier_id,"category_added",`Product category ${p.name} added`,u);return safeJson(r)},
 async renameCategory(id,p){return safeJson((await query("UPDATE supplier_product_categories SET name=$1 WHERE id=$2 RETURNING *",[p.name,id])).rows[0])},
 async deleteCategory(id){await query("DELETE FROM supplier_product_categories WHERE id=$1",[id]);return {message:"Category removed."}},
 async addGrade(categoryId,p,u){const x=(await query("SELECT w.supplier_id FROM supplier_product_categories c JOIN supplier_warehouses w ON w.id=c.warehouse_id WHERE c.id=$1",[categoryId])).rows[0];const r=(await query("INSERT INTO supplier_grades(category_id,name) VALUES($1,$2) RETURNING *",[categoryId,p.name])).rows[0];await activity(x.supplier_id,"grade_added",`Grade ${p.name} added`,u);return safeJson(r)},
 async renameGrade(id,p){return safeJson((await query("UPDATE supplier_grades SET name=$1 WHERE id=$2 RETURNING *",[p.name,id])).rows[0])},
 async deleteGrade(id){await query("DELETE FROM supplier_grades WHERE id=$1",[id]);return {message:"Grade removed."}},
 async savePrice(gradeId,p,u){const info=(await query("SELECT w.supplier_id FROM supplier_grades g JOIN supplier_product_categories c ON c.id=g.category_id JOIN supplier_warehouses w ON w.id=c.warehouse_id WHERE g.id=$1",[gradeId])).rows[0];const hours=+(await query("SELECT price_validity_hours FROM procurement_settings WHERE id=1")).rows[0].price_validity_hours;const old=(await query("SELECT * FROM supplier_grade_prices WHERE grade_id=$1 ORDER BY created_at DESC LIMIT 1",[gradeId])).rows[0];await query("UPDATE supplier_grade_prices SET is_active=FALSE WHERE grade_id=$1",[gradeId]);const r=(await query("INSERT INTO supplier_grade_prices(grade_id,purchase_price,remarks,expires_at,updated_by) VALUES($1,$2,$3,now()+($4||' hours')::interval,$5) RETURNING *",[gradeId,p.purchase_price,p.remarks,hours,u])).rows[0];for(const field of ["purchase_price","remarks"])if(String(old?.[field]??"")!==String(r[field]??""))await query("INSERT INTO supplier_price_cell_history(price_id,field_name,previous_value,updated_value,change_remarks,updated_by) VALUES($1,$2,$3,$4,$5,$6)",[r.id,field,old?.[field],r[field],p.change_remarks,u]);await activity(info.supplier_id,"price_updated",`Grade price updated to ₹${p.purchase_price}/Kg`,u,{grade_id:gradeId});return safeJson(r)},
 async history(gradeId,field){return (await query(`SELECT h.*,u.name updated_by_name FROM supplier_price_cell_history h JOIN supplier_grade_prices p ON p.id=h.price_id LEFT JOIN users u ON u.id=h.updated_by WHERE p.grade_id=$1 AND ($2::text IS NULL OR h.field_name=$2) ORDER BY changed_at DESC`,[gradeId,field||null])).rows.map(safeJson)},
 async settings(){return safeJson((await query("SELECT * FROM procurement_settings WHERE id=1")).rows[0])},
 async updateSettings(p){return safeJson((await query("UPDATE procurement_settings SET price_validity_hours=$1,preference_hierarchy=COALESCE($2,preference_hierarchy),updated_at=now() WHERE id=1 RETURNING *",[p.price_validity_hours,p.preference_hierarchy])).rows[0])},
 async preferences(){return (await query("SELECT p.*,s.group_name supplier_name,w.warehouse_name FROM procurement_preferences p JOIN suppliers s ON s.id=p.supplier_id LEFT JOIN supplier_warehouses w ON w.id=p.warehouse_id ORDER BY preference_level,priority")).rows.map(safeJson)},
 async savePreference(p){return safeJson((await query("INSERT INTO procurement_preferences(preference_level,buyer_id,category_name,grade_name,supplier_id,warehouse_id,priority) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[p.preference_level,p.buyer_id,p.category_name,p.grade_name,p.supplier_id,p.warehouse_id,p.priority||1])).rows[0])},
 async resolve(p){const pref=(await query(`SELECT pr.*,s.group_name supplier_name,w.warehouse_name,gp.purchase_price FROM procurement_preferences pr JOIN suppliers s ON s.id=pr.supplier_id LEFT JOIN supplier_warehouses w ON w.id=pr.warehouse_id LEFT JOIN supplier_product_categories c ON c.warehouse_id=w.id AND c.name=$2 LEFT JOIN supplier_grades g ON g.category_id=c.id AND g.name=$3 LEFT JOIN LATERAL(SELECT purchase_price FROM supplier_grade_prices WHERE grade_id=g.id AND is_active AND expires_at>now() ORDER BY created_at DESC LIMIT 1)gp ON true WHERE pr.is_active AND s.is_active AND pr.grade_name=$3 AND (pr.category_name IS NULL OR pr.category_name=$2) AND (pr.buyer_id IS NULL OR pr.buyer_id=$1) AND gp.purchase_price IS NOT NULL ORDER BY CASE pr.preference_level WHEN 'customer_product_grade' THEN 1 WHEN 'product_grade' THEN 2 ELSE 3 END,pr.priority LIMIT 1`,[p.buyer_id||null,p.category_name,p.grade_name])).rows[0];if(pref)return safeJson({...pref,source:pref.preference_level});const l1=(await query(`SELECT s.id supplier_id,s.group_name supplier_name,w.id warehouse_id,w.warehouse_name,p.purchase_price FROM supplier_grade_prices p JOIN supplier_grades g ON g.id=p.grade_id JOIN supplier_product_categories c ON c.id=g.category_id JOIN supplier_warehouses w ON w.id=c.warehouse_id JOIN suppliers s ON s.id=w.supplier_id WHERE c.name=$1 AND g.name=$2 AND p.is_active AND p.expires_at>now() AND s.is_active ORDER BY p.purchase_price LIMIT 1`,[p.category_name,p.grade_name])).rows[0];return l1?safeJson({...l1,source:"lowest_valid_price"}):null}
};
