import { getClient, query } from "../db.js";
import { safeJson } from "../utils.js";

const rows = async (sql, values = []) => (await query(sql, values)).rows.map(safeJson);
const required = (p, fields) => { for (const field of fields) if (p[field] === undefined || p[field] === null || p[field] === "") throw new Error(`${field.replaceAll("_", " ")} is required.`); };
const interest = (amount, rate, days) => Math.round((Number(amount) * Number(rate) / 100 / 365 * Number(days) + Number.EPSILON) * 100) / 100;

export const WorkingCapitalService = {
 async masters() {
  const [banks, accounts, suppliers, warehouses, orders] = await Promise.all([
   rows("SELECT * FROM procurement_banks ORDER BY bank_name"),
   rows(`SELECT a.*,b.bank_name,(a.sanctioned_cc_limit-a.current_utilization) available_cc_limit FROM procurement_bank_accounts a JOIN procurement_banks b ON b.id=a.bank_id ORDER BY b.bank_name,a.account_number`),
   rows("SELECT id,group_name FROM suppliers WHERE is_active ORDER BY group_name"),
   rows("SELECT w.id,w.supplier_id,w.warehouse_name,w.dispatch_location FROM supplier_warehouses w JOIN suppliers s ON s.id=w.supplier_id WHERE s.is_active ORDER BY s.group_name,w.warehouse_name"),
   rows("SELECT id,order_number,inquiry_number,supplier_id,product_category,grade,quantity_kg,purchase_price_per_kg,total_order_value FROM orders WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT 500")
  ]); return { banks, accounts, suppliers, warehouses, orders };
 },
 async createBank(p) { required(p,["bank_name"]); return safeJson((await query("INSERT INTO procurement_banks(bank_name,status,remarks)VALUES($1,$2,$3)RETURNING *",[p.bank_name,p.status||"Active",p.remarks])).rows[0]); },
 async updateBank(id,p) { return safeJson((await query("UPDATE procurement_banks SET bank_name=COALESCE($1,bank_name),status=COALESCE($2,status),remarks=COALESCE($3,remarks),updated_at=now() WHERE id=$4 RETURNING *",[p.bank_name,p.status,p.remarks,id])).rows[0]); },
 async createAccount(p,user) {
  required(p,["bank_id","account_number","account_type"]); if(p.has_cc_facility && !(+p.sanctioned_cc_limit>0))throw new Error("A CC account requires a sanctioned limit.");
  const c=await getClient(); try { await c.query("BEGIN"); const a=(await c.query(`INSERT INTO procurement_bank_accounts(bank_id,account_number,account_type,has_cc_facility,sanctioned_cc_limit,current_cc_rate,rate_effective_from,status,remarks)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)RETURNING *`,[p.bank_id,p.account_number,p.account_type,p.has_cc_facility||false,p.sanctioned_cc_limit||0,p.has_cc_facility?p.current_cc_rate||0:0,p.rate_effective_from||null,p.status||"Active",p.remarks])).rows[0]; if(a.has_cc_facility)await c.query("INSERT INTO procurement_cc_rate_history(account_id,annual_rate,effective_from,remarks,created_by)VALUES($1,$2,COALESCE($3,CURRENT_DATE),$4,$5)",[a.id,a.current_cc_rate,a.rate_effective_from,p.remarks,user]); await c.query("COMMIT"); return safeJson(a); } catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}
 },
 async updateAccount(id,p,user) {
  const old=(await query("SELECT * FROM procurement_bank_accounts WHERE id=$1",[id])).rows[0]; if(!old)throw new Error("Bank account not found."); const rate=p.current_cc_rate===undefined?+old.current_cc_rate:+p.current_cc_rate, effective=p.rate_effective_from||new Date().toISOString().slice(0,10);
  const c=await getClient();try{await c.query("BEGIN");if(rate!==+old.current_cc_rate){await c.query("UPDATE procurement_cc_rate_history SET effective_to=$1::date-1 WHERE account_id=$2 AND effective_to IS NULL AND effective_from<$1",[effective,id]);await c.query(`INSERT INTO procurement_cc_rate_history(account_id,annual_rate,effective_from,remarks,created_by)VALUES($1,$2,$3,$4,$5) ON CONFLICT(account_id,effective_from)DO UPDATE SET annual_rate=EXCLUDED.annual_rate,remarks=EXCLUDED.remarks,created_by=EXCLUDED.created_by`,[id,rate,effective,p.rate_change_remarks||p.remarks,user])}const a=(await c.query(`UPDATE procurement_bank_accounts SET account_number=COALESCE($1,account_number),account_type=COALESCE($2,account_type),has_cc_facility=COALESCE($3,has_cc_facility),sanctioned_cc_limit=COALESCE($4,sanctioned_cc_limit),current_cc_rate=$5,rate_effective_from=$6,status=COALESCE($7,status),remarks=COALESCE($8,remarks),updated_at=now() WHERE id=$9 RETURNING *`,[p.account_number,p.account_type,p.has_cc_facility,p.sanctioned_cc_limit,rate,effective,p.status,p.remarks,id])).rows[0];await c.query("COMMIT");return safeJson(a)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}
 },
 async rateHistory(id){return rows("SELECT h.*,u.name created_by_name FROM procurement_cc_rate_history h LEFT JOIN users u ON u.id=h.created_by WHERE account_id=$1 ORDER BY effective_from DESC",[id])},
 async list(p={}){const v=[],w=[];for(const [key,col]of Object.entries({supplier_id:"p.supplier_id",warehouse_id:"p.warehouse_id",bank_id:"p.bank_id",account_id:"p.account_id",funding_type:"p.funding_type",payment_status:"p.payment_status",order_id:"p.order_id"}))if(p[key]){v.push(p[key]);w.push(`${col}=$${v.length}`)}if(p.product){v.push(p.product);w.push(`p.product_category=$${v.length}`)}if(p.grade){v.push(p.grade);w.push(`p.grade=$${v.length}`)}if(p.date_from){v.push(p.date_from);w.push(`COALESCE(p.supplier_invoice_date,p.created_at::date)>=$${v.length}`)}if(p.date_to){v.push(p.date_to);w.push(`COALESCE(p.supplier_invoice_date,p.created_at::date)<=$${v.length}`)}return rows(`SELECT * FROM supplier_procurement_economics_view p ${w.length?`WHERE ${w.join(" AND ")}`:""} ORDER BY p.created_at DESC`,v)},
 async summary(supplierId){const r=(await query(`SELECT COALESCE(sum(quantity_kg),0) total_purchase_volume,COALESCE(sum(supplier_cost),0) total_purchase_value,count(*)::int number_of_orders,COALESCE(avg(supplier_price),0) average_purchase_price,COALESCE(min(supplier_price),0) lowest_purchase_price,COALESCE(max(supplier_price),0) highest_purchase_price,COALESCE(sum(financing_cost),0) total_financing_cost,COALESCE(sum(logistics_cost),0) total_logistics_cost,COALESCE(sum(financing_cost)/NULLIF(sum(quantity_kg),0),0) average_cc_cost_per_kg,COALESCE(sum(true_procurement_cost),0) total_procurement_cost FROM supplier_procurement_economics_view WHERE supplier_id=$1`,[supplierId])).rows[0];return safeJson(r)},
 async create(p,user){required(p,["supplier_id","warehouse_id","product_category","grade","quantity_kg","supplier_price","funding_type"]);const cc=p.funding_type==="CC Funds";const c=await getClient();try{await c.query("BEGIN");let account=null,rate=0;if(cc){required(p,["account_id","cc_amount","cc_utilization_date"]);account=(await c.query("SELECT * FROM procurement_bank_accounts WHERE id=$1 AND status='Active' FOR UPDATE",[p.account_id])).rows[0];if(!account?.has_cc_facility)throw new Error("Select an active account with a CC facility.");if(+account.current_utilization + +p.cc_amount > +account.sanctioned_cc_limit)throw new Error("CC amount exceeds the account's available limit.");rate=+account.current_cc_rate;await c.query("UPDATE procurement_bank_accounts SET current_utilization=current_utilization+$1,updated_at=now() WHERE id=$2",[p.cc_amount,p.account_id])}const estimatedDays=Math.max(+p.estimated_cc_days||0,0),estimated=cc?interest(p.cc_amount,rate,estimatedDays):0;const x=(await c.query(`INSERT INTO supplier_procurement_transactions(supplier_id,warehouse_id,order_id,transaction_id,product_category,grade,quantity_kg,supplier_price,supplier_invoice_number,supplier_invoice_date,purchase_order_reference,payment_amount,payment_date,payment_status,bank_id,account_id,funding_type,cc_amount,cc_rate,cc_utilization_date,estimated_cc_interest,logistics_reference,logistics_cost,other_costs,buyer_revenue,remarks,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$27)RETURNING *`,[p.supplier_id,p.warehouse_id,p.order_id||null,p.transaction_id||null,p.product_category,p.grade,p.quantity_kg,p.supplier_price,p.supplier_invoice_number,p.supplier_invoice_date||null,p.purchase_order_reference,p.payment_amount||0,p.payment_date||null,p.payment_status||"Pending",cc?account.bank_id:p.bank_id||null,p.account_id||null,p.funding_type,cc?p.cc_amount:0,rate,p.cc_utilization_date||null,estimated,p.logistics_reference,p.logistics_cost||0,p.other_costs||0,p.buyer_revenue||0,p.remarks,user])).rows[0];await c.query("INSERT INTO supplier_procurement_audit(transaction_id,action,updated_values,changed_by)VALUES($1,'Created',$2,$3)",[x.id,x,user]);await c.query("COMMIT");return safeJson(x)}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}},
 async settle(id,p,user){required(p,["cc_settlement_date"]);const c=await getClient();try{await c.query("BEGIN");const old=(await c.query("SELECT * FROM supplier_procurement_transactions WHERE id=$1 FOR UPDATE",[id])).rows[0];if(!old)throw new Error("Procurement transaction not found.");if(old.funding_type!=="CC Funds")throw new Error("Only CC-funded transactions can be settled.");if(old.cc_settlement_date)throw new Error("This CC utilization is already settled.");const days=Math.max(Math.round((new Date(p.cc_settlement_date)-new Date(old.cc_utilization_date))/86400000),0),actual=interest(old.cc_amount,old.cc_rate,days);const x=(await c.query("UPDATE supplier_procurement_transactions SET cc_settlement_date=$1,actual_cc_interest=$2,accrued_cc_interest=$2,updated_by=$3,updated_at=now() WHERE id=$4 RETURNING *",[p.cc_settlement_date,actual,user,id])).rows[0];await c.query("UPDATE procurement_bank_accounts SET current_utilization=GREATEST(current_utilization-$1,0),updated_at=now() WHERE id=$2",[old.cc_amount,old.account_id]);await c.query("INSERT INTO supplier_procurement_audit(transaction_id,action,previous_values,updated_values,changed_by)VALUES($1,'CC Settled',$2,$3,$4)",[id,old,x,user]);await c.query("COMMIT");return safeJson({...x,cc_days:days})}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}},
 async history(id){return rows("SELECT a.*,u.name changed_by_name FROM supplier_procurement_audit a LEFT JOIN users u ON u.id=a.changed_by WHERE transaction_id=$1 ORDER BY changed_at DESC",[id])},
 async accrue(){return safeJson((await query(`WITH x AS(UPDATE supplier_procurement_transactions SET accrued_cc_interest=round((cc_amount*cc_rate/100/365*GREATEST(CURRENT_DATE-cc_utilization_date,0))::numeric,2),updated_at=now() WHERE funding_type='CC Funds' AND cc_settlement_date IS NULL RETURNING id)SELECT count(*)::int updated FROM x`)).rows[0])},
 async dashboard(){const [bank,account,supplier,order]=await Promise.all([rows(`SELECT b.id,b.bank_name,COALESCE(sum(a.sanctioned_cc_limit),0) total_cc_limit,COALESCE(sum(a.current_utilization),0) utilized_cc,COALESCE(sum(a.sanctioned_cc_limit-a.current_utilization),0) available_cc_limit,round((100*sum(a.current_utilization)/NULLIF(sum(a.sanctioned_cc_limit),0))::numeric,2) utilization_percent,COALESCE(sum(p.accrued_cc_interest)FILTER(WHERE p.cc_settlement_date IS NULL),0) accrued_interest,COALESCE(sum(p.actual_cc_interest),0) actual_interest FROM procurement_banks b LEFT JOIN procurement_bank_accounts a ON a.bank_id=b.id LEFT JOIN supplier_procurement_transactions p ON p.account_id=a.id GROUP BY b.id ORDER BY b.bank_name`),rows(`SELECT a.id,b.bank_name,a.account_number,a.sanctioned_cc_limit cc_limit,a.current_utilization,a.sanctioned_cc_limit-a.current_utilization available_limit,a.current_cc_rate rate,COALESCE(sum(p.accrued_cc_interest)FILTER(WHERE p.cc_settlement_date IS NULL),0) accrued_interest FROM procurement_bank_accounts a JOIN procurement_banks b ON b.id=a.bank_id LEFT JOIN supplier_procurement_transactions p ON p.account_id=a.id GROUP BY a.id,b.bank_name ORDER BY b.bank_name,a.account_number`),rows(`SELECT supplier_id,supplier_name,sum(CASE WHEN funding_type='CC Funds' THEN supplier_cost ELSE 0 END) cc_funded_procurement,sum(financing_cost) interest_cost FROM supplier_procurement_economics_view GROUP BY supplier_id,supplier_name ORDER BY cc_funded_procurement DESC`),rows(`SELECT order_id,sum(financing_cost) financing_cost,COALESCE(sum(financing_cost)/NULLIF(sum(quantity_kg),0),0) financing_cost_per_kg FROM supplier_procurement_economics_view WHERE order_id IS NOT NULL GROUP BY order_id ORDER BY order_id DESC`)]);return{bank,account,supplier,order}}
};
