BEGIN;
CREATE SEQUENCE IF NOT EXISTS sales_inquiry_seq START 1;
ALTER TABLE buyers ADD COLUMN IF NOT EXISTS group_margin_per_kg NUMERIC(14,4) DEFAULT 0;
ALTER TABLE buyers ADD COLUMN IF NOT EXISTS credit_cost_per_kg NUMERIC(14,4) DEFAULT 0;
ALTER TABLE buyers ADD COLUMN IF NOT EXISTS payment_terms TEXT;
ALTER TABLE buyers ADD COLUMN IF NOT EXISTS latest_quoted_price NUMERIC(14,4);
CREATE TABLE sales_master_values(id BIGSERIAL PRIMARY KEY,master_type TEXT NOT NULL CHECK(master_type IN('inquiry_type','inquiry_source','sales_stage','additional_charge')),label TEXT NOT NULL,is_active BOOLEAN DEFAULT TRUE,sort_order INTEGER DEFAULT 0,UNIQUE(master_type,label));
INSERT INTO sales_master_values(master_type,label,sort_order) VALUES
('inquiry_type','Inbound',1),('inquiry_type','Outbound',2),('inquiry_source','Website',1),('inquiry_source','Existing Customer',2),('inquiry_source','Phone',3),('inquiry_source','WhatsApp',4),('inquiry_source','Email',5),('inquiry_source','Referral',6),('inquiry_source','Cold Call',7),('inquiry_source','Sales Visit',8),('inquiry_source','LinkedIn',9),('inquiry_source','Email Campaign',10),('inquiry_source','Trade Show',11),('inquiry_source','Other',12),
('sales_stage','Inquiry Created',1),('sales_stage','Quotation Generated',2),('sales_stage','Quotation Shared',3),('sales_stage','Negotiation',4),('sales_stage','Won',5),('sales_stage','PI Generated',6),('sales_stage','Order Confirmed',7),('sales_stage','Supplier Ordered',8),('sales_stage','Dispatch Planned',9),('sales_stage','Invoice Generated',10),('sales_stage','Dispatched',11),('sales_stage','Delivered',12),('sales_stage','Completed',13),('sales_stage','Closed',14),('sales_stage','Lost',15),('sales_stage','Cancelled',16),('sales_stage','On Hold',17),
('additional_charge','Packaging',1),('additional_charge','Handling',2),('additional_charge','Insurance',3),('additional_charge','Documentation',4),('additional_charge','Loading',5),('additional_charge','Unloading',6),('additional_charge','Miscellaneous',7) ON CONFLICT DO NOTHING;
CREATE TABLE sales_transactions(id BIGSERIAL PRIMARY KEY,inquiry_number TEXT NOT NULL UNIQUE DEFAULT('INQ-'||to_char(CURRENT_DATE,'YYYY')||'-'||lpad(nextval('sales_inquiry_seq')::text,6,'0')),buyer_id BIGINT NOT NULL REFERENCES buyers(id) ON DELETE RESTRICT,inquiry_type TEXT NOT NULL,inquiry_source TEXT NOT NULL,inquiry_date DATE NOT NULL DEFAULT CURRENT_DATE,sales_representative INTEGER REFERENCES users(id) ON DELETE SET NULL,current_stage TEXT NOT NULL DEFAULT 'Inquiry Created',status TEXT NOT NULL DEFAULT 'Open',active_revision_id BIGINT,remarks TEXT,pi_required BOOLEAN DEFAULT FALSE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),deleted_at TIMESTAMPTZ);
CREATE TABLE sales_transaction_products(id BIGSERIAL PRIMARY KEY,transaction_id BIGINT NOT NULL REFERENCES sales_transactions(id) ON DELETE CASCADE,product_category TEXT NOT NULL,grade TEXT NOT NULL,quantity_kg NUMERIC(14,3) NOT NULL CHECK(quantity_kg>0),dispatch_from_warehouse_id BIGINT REFERENCES supplier_warehouses(id) ON DELETE SET NULL,delivery_to TEXT NOT NULL,delivery_pincode TEXT,logistics_lane_id BIGINT REFERENCES logistics_lanes(id) ON DELETE SET NULL,preferred_supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,supplier_price NUMERIC(14,4) DEFAULT 0,logistics_cost NUMERIC(14,4) DEFAULT 0,additional_charges NUMERIC(14,4) DEFAULT 0,group_margin NUMERIC(14,4) DEFAULT 0,credit_cost NUMERIC(14,4) DEFAULT 0,final_quotation_price NUMERIC(14,4) GENERATED ALWAYS AS(COALESCE(supplier_price,0)+COALESCE(logistics_cost,0)+COALESCE(additional_charges,0)+COALESCE(group_margin,0)+COALESCE(credit_cost,0)) STORED,quoted_price NUMERIC(14,4),remarks TEXT,sort_order INTEGER DEFAULT 0,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE sales_product_charges(id BIGSERIAL PRIMARY KEY,product_id BIGINT NOT NULL REFERENCES sales_transaction_products(id) ON DELETE CASCADE,charge_type TEXT NOT NULL,amount_per_kg NUMERIC(14,4) NOT NULL DEFAULT 0,remarks TEXT);
CREATE TABLE sales_quote_revisions(id BIGSERIAL PRIMARY KEY,transaction_id BIGINT NOT NULL REFERENCES sales_transactions(id) ON DELETE CASCADE,revision_number INTEGER NOT NULL,is_active BOOLEAN DEFAULT FALSE,remarks TEXT,pricing_changes JSONB DEFAULT '{}',created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now(),UNIQUE(transaction_id,revision_number));
CREATE TABLE sales_quote_revision_lines(id BIGSERIAL PRIMARY KEY,revision_id BIGINT NOT NULL REFERENCES sales_quote_revisions(id) ON DELETE CASCADE,product_id BIGINT REFERENCES sales_transaction_products(id) ON DELETE SET NULL,product_category TEXT,grade TEXT,quantity_kg NUMERIC(14,3),supplier_price NUMERIC(14,4),logistics_cost NUMERIC(14,4),additional_charges NUMERIC(14,4),group_margin NUMERIC(14,4),credit_cost NUMERIC(14,4),final_quotation_price NUMERIC(14,4));
ALTER TABLE sales_transactions ADD CONSTRAINT sales_transaction_active_revision_fk FOREIGN KEY(active_revision_id) REFERENCES sales_quote_revisions(id) ON DELETE SET NULL;
CREATE TABLE sales_communications(id BIGSERIAL PRIMARY KEY,transaction_id BIGINT NOT NULL REFERENCES sales_transactions(id) ON DELETE CASCADE,communication_type TEXT NOT NULL,message TEXT NOT NULL,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE sales_stage_history(id BIGSERIAL PRIMARY KEY,transaction_id BIGINT NOT NULL REFERENCES sales_transactions(id) ON DELETE CASCADE,previous_stage TEXT,new_stage TEXT NOT NULL,remarks TEXT,changed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,changed_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE sales_documents(id BIGSERIAL PRIMARY KEY,transaction_id BIGINT NOT NULL REFERENCES sales_transactions(id) ON DELETE CASCADE,document_type TEXT NOT NULL CHECK(document_type IN('tax_invoice','customer_po','supplier_po','dispatch_note','pod')),document_number TEXT,file_name TEXT,content_type TEXT,document_content BYTEA,document_data JSONB DEFAULT '{}',created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE orders ADD COLUMN IF NOT EXISTS transaction_id BIGINT REFERENCES sales_transactions(id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS transaction_product_id BIGINT REFERENCES sales_transaction_products(id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS inquiry_number TEXT;ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_number TEXT;ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_date DATE;ALTER TABLE orders ADD COLUMN IF NOT EXISTS invoice_value NUMERIC(16,2);ALTER TABLE orders ADD COLUMN IF NOT EXISTS place_of_supply TEXT;ALTER TABLE orders ADD COLUMN IF NOT EXISTS transporter_id BIGINT REFERENCES logistics_transporters(id) ON DELETE SET NULL;ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_terms TEXT;ALTER TABLE orders ADD COLUMN IF NOT EXISTS dispatch_date DATE;ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_date DATE;ALTER TABLE orders ADD COLUMN IF NOT EXISTS due_date DATE;ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_received NUMERIC(16,2) DEFAULT 0;ALTER TABLE orders ADD COLUMN IF NOT EXISTS future_payment_behaviour TEXT;
CREATE INDEX idx_sales_transactions_buyer ON sales_transactions(buyer_id,created_at DESC);CREATE INDEX idx_sales_transactions_stage ON sales_transactions(current_stage,updated_at DESC);CREATE INDEX idx_sales_products_transaction ON sales_transaction_products(transaction_id,sort_order);CREATE INDEX idx_sales_revisions_transaction ON sales_quote_revisions(transaction_id,revision_number DESC);CREATE INDEX idx_sales_communications_transaction ON sales_communications(transaction_id,created_at DESC);CREATE INDEX idx_orders_transaction ON orders(transaction_id);CREATE UNIQUE INDEX uq_orders_transaction_product ON orders(transaction_product_id);
COMMIT;
