BEGIN;
CREATE TABLE IF NOT EXISTS settings_master_types(id BIGSERIAL PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,category TEXT NOT NULL,description TEXT,fields JSONB NOT NULL DEFAULT '[]',is_active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS settings_master_records(id BIGSERIAL PRIMARY KEY,master_type_id BIGINT NOT NULL REFERENCES settings_master_types(id) ON DELETE RESTRICT,code TEXT NOT NULL,name TEXT NOT NULL,parent_id BIGINT REFERENCES settings_master_records(id) ON DELETE RESTRICT,data JSONB NOT NULL DEFAULT '{}',sort_order INTEGER DEFAULT 0,is_active BOOLEAN DEFAULT TRUE,created_by INTEGER REFERENCES users(id),updated_by INTEGER REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(master_type_id,code));
CREATE TABLE IF NOT EXISTS settings_business_rules(id BIGSERIAL PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,category TEXT NOT NULL,description TEXT,rule_type TEXT NOT NULL DEFAULT 'Formula',formula TEXT,configuration JSONB NOT NULL DEFAULT '{}',effective_from DATE DEFAULT CURRENT_DATE,effective_to DATE,priority INTEGER DEFAULT 0,is_active BOOLEAN DEFAULT TRUE,created_by INTEGER REFERENCES users(id),updated_by INTEGER REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS settings_number_series(id BIGSERIAL PRIMARY KEY,document_type TEXT NOT NULL UNIQUE,prefix TEXT DEFAULT '',suffix TEXT DEFAULT '',separator TEXT DEFAULT '-',padding INTEGER DEFAULT 6,next_number BIGINT DEFAULT 1,reset_frequency TEXT DEFAULT 'Never',include_financial_year BOOLEAN DEFAULT FALSE,sample TEXT,is_active BOOLEAN DEFAULT TRUE,updated_by INTEGER REFERENCES users(id),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS settings_document_templates(id BIGSERIAL PRIMARY KEY,template_type TEXT NOT NULL,name TEXT NOT NULL,subject TEXT,body TEXT NOT NULL DEFAULT '',header_html TEXT,footer_html TEXT,placeholders JSONB DEFAULT '[]',version INTEGER DEFAULT 1,is_default BOOLEAN DEFAULT FALSE,is_active BOOLEAN DEFAULT TRUE,created_by INTEGER REFERENCES users(id),updated_by INTEGER REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(template_type,name,version));
CREATE TABLE IF NOT EXISTS settings_communication_templates(id BIGSERIAL PRIMARY KEY,channel TEXT NOT NULL CHECK(channel IN('Email','WhatsApp','SMS','In-App')),template_type TEXT NOT NULL,name TEXT NOT NULL,subject TEXT,body TEXT NOT NULL,variables JSONB DEFAULT '[]',is_active BOOLEAN DEFAULT TRUE,created_by INTEGER REFERENCES users(id),updated_by INTEGER REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(channel,name));
CREATE TABLE IF NOT EXISTS settings_approval_workflows(id BIGSERIAL PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,approval_type TEXT NOT NULL,trigger_conditions JSONB DEFAULT '{}',is_active BOOLEAN DEFAULT TRUE,created_by INTEGER REFERENCES users(id),updated_by INTEGER REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS settings_approval_levels(id BIGSERIAL PRIMARY KEY,workflow_id BIGINT NOT NULL REFERENCES settings_approval_workflows(id) ON DELETE CASCADE,level_number INTEGER NOT NULL,role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,min_approvals INTEGER DEFAULT 1,can_reject BOOLEAN DEFAULT TRUE,escalation_hours INTEGER,UNIQUE(workflow_id,level_number));
CREATE TABLE IF NOT EXISTS settings_access_permissions(id BIGSERIAL PRIMARY KEY,role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,scope_type TEXT NOT NULL CHECK(scope_type IN('Module','Section','Table','View','Record','Field','Button','Workflow','Report','Dashboard','Document')),scope_key TEXT NOT NULL,permissions JSONB NOT NULL DEFAULT '{"view":false,"create":false,"edit":false,"delete":false,"approve":false,"export":false,"print":false}',conditions JSONB DEFAULT '{}',updated_by INTEGER REFERENCES users(id),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(role_id,scope_type,scope_key));
CREATE TABLE IF NOT EXISTS settings_system_preferences(id BIGSERIAL PRIMARY KEY,section TEXT NOT NULL,key TEXT NOT NULL,value JSONB NOT NULL DEFAULT 'null',data_type TEXT DEFAULT 'text',description TEXT,is_secret BOOLEAN DEFAULT FALSE,updated_by INTEGER REFERENCES users(id),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(section,key));
CREATE TABLE IF NOT EXISTS settings_configuration_history(id BIGSERIAL PRIMARY KEY,entity_type TEXT NOT NULL,entity_id BIGINT,configuration_key TEXT,previous_value JSONB,new_value JSONB,changed_by INTEGER REFERENCES users(id),reason TEXT NOT NULL,changed_at TIMESTAMPTZ DEFAULT now());
INSERT INTO settings_master_types(code,name,category) VALUES
('product_categories','Product Categories','Product'),('products','Products','Product'),('grades','Grades','Product'),('applications','Applications','Product'),('sub_applications','Sub Applications','Product'),('hsn_codes','HSN Codes','Product'),
('countries','Countries','Geography'),('states','States','Geography'),('districts','Districts','Geography'),('cities','Cities','Geography'),('pincodes','Pincodes','Geography'),
('warehouses','Warehouses','Warehouse'),('warehouse_addresses','Warehouse Addresses','Warehouse'),('warehouse_types','Warehouse Types','Warehouse'),
('payment_terms','Payment Terms','Commercial'),('credit_periods','Credit Periods','Commercial'),('credit_cost_slabs','Credit Cost Slabs','Commercial'),('margin_categories','Margin Categories','Commercial'),('tax_categories','Tax Categories','Commercial'),('currencies','Currency','Commercial'),('units','Units of Measurement','Commercial'),
('quantity_slabs','Quantity Slabs','Logistics'),('transporters','Transporters','Logistics'),('vehicle_types','Vehicle Types','Logistics'),('lane_categories','Lane Categories','Logistics'),
('lead_types','Lead Types','CRM'),('inquiry_types','Inquiry Types','CRM'),('lead_sources','Lead Sources','CRM'),('lead_statuses','Lead Status','CRM'),('order_statuses','Order Status','CRM'),('commercial_statuses','Commercial Status','CRM'),('payment_statuses','Payment Status','CRM'),('reminder_types','Reminder Types','CRM'),('task_categories','Task Categories','CRM'),('priority_levels','Priority Levels','CRM') ON CONFLICT(code) DO NOTHING;
INSERT INTO settings_number_series(document_type,prefix,padding,include_financial_year) VALUES ('Inquiry Number','INQ',6,TRUE),('Sales Order','ORD',6,TRUE),('Commercial Number','COM',7,TRUE),('Purchase Number','PO',6,TRUE),('Invoice Number','INV',6,TRUE),('Freight Voucher','FRT',6,TRUE),('Expense Voucher','EXP',6,TRUE),('Payment Voucher','PAY',6,TRUE) ON CONFLICT(document_type) DO NOTHING;
INSERT INTO settings_business_rules(code,name,category,rule_type) VALUES ('default_credit_cost','Default Credit Cost Formula','Commercial','Formula'),('margin_formula','Margin Formula','Commercial','Formula'),('freight_prediction','Freight Prediction Parameters','Logistics','Parameters'),('freight_validity','Freight Validity','Logistics','Duration'),('supplier_price_validity','Supplier Price Validity','Supplier','Duration'),('lead_score','Lead Score Formula','CRM','Formula'),('follow_up','Follow-up Formula','CRM','Formula'),('reminder_logic','Reminder Logic','Notification','Conditions'),('credit_limit','Credit Limit Rules','Finance','Conditions'),('approval_thresholds','Approval Thresholds','Approval','Threshold'),('working_days','Working Days','Calendar','Calendar'),('company_holidays','Company Holidays','Calendar','Calendar') ON CONFLICT(code) DO NOTHING;
INSERT INTO settings_system_preferences(section,key,value,data_type,description) VALUES ('Company','company_details','{}','json','Legal name and registered address'),('Tax','gst','null','text','Company GST number'),('Tax','pan','null','text','Company PAN'),('Banking','bank_accounts','[]','json','Company bank accounts'),('Documents','invoice_footer','null','richtext','Invoice footer'),('Email','email_server','{}','json','SMTP configuration reference'),('Notifications','notification_preferences','{}','json','Notification rules'),('Localization','currency','"INR"','text','Base currency'),('Localization','time_zone','"Asia/Kolkata"','text','System time zone'),('Finance','financial_year','"April-March"','text','Financial year') ON CONFLICT(section,key) DO NOTHING;
CREATE INDEX IF NOT EXISTS idx_settings_master_records_type ON settings_master_records(master_type_id,is_active,sort_order);
CREATE INDEX IF NOT EXISTS idx_settings_history_entity ON settings_configuration_history(entity_type,entity_id,changed_at DESC);
UPDATE roles SET permissions=jsonb_set(COALESCE(permissions,'{}'::jsonb),'{modules,settings}','true'::jsonb,true);
COMMIT;
