BEGIN;
WITH t AS(INSERT INTO logistics_transporters(company_name,gst_number,pan_number,contact_person,phone_number,email) VALUES('Dummy Fast Freight','24AAAAA4444A1Z5','AAAAA4444A','Demo Contact','9000000020','freight@example.com') RETURNING id),l AS(INSERT INTO logistics_lanes(pickup_warehouse,pickup_district,pickup_pincode,delivery_district,delivery_pincode,notes) VALUES('Ahmedabad Warehouse','Ahmedabad','380001','Indore','452001','Dummy logistics lane') RETURNING id)
INSERT INTO logistics_shipments(lane_id,transporter_id,quantity_kg,freight_rate_per_kg,shipment_weight_kg,order_reference,invoice_number,delivery_status,delivered_at,expected_delivery_at) SELECT l.id,t.id,5000,3.25,5000,'DUMMY-ORDER-1','DUMMY-INV-1','Delivered',now(),now()-interval '1 hour' FROM l,t;
INSERT INTO logistics_cost_register(shipment_id,order_reference,invoice_number,freight_cost,door_delivery_charges,porter_charges,other_charges,remarks) SELECT id,order_reference,invoice_number,16250,1000,500,250,'Dummy logistics cost' FROM logistics_shipments WHERE order_reference='DUMMY-ORDER-1';

WITH t AS(INSERT INTO logistics_transporters(company_name,gst_number,pan_number,contact_person,phone_number,email,office_address) VALUES('Dummy Reliable Transport','27BBBBB5555B1Z5','BBBBB5555B','Demo Operations','9000000021','reliable@example.com','Dummy Transport Nagar, Mumbai') RETURNING id),l AS(INSERT INTO logistics_lanes(pickup_warehouse,pickup_district,pickup_pincode,delivery_district,delivery_pincode,notes,road_conditions,special_instructions) VALUES('Bhiwandi Warehouse','Thane','421302','Jaipur','302001','Dummy west-to-north lane','Normal highway conditions','Delivery appointment required') RETURNING id)
INSERT INTO logistics_shipments(lane_id,transporter_id,quantity_kg,freight_rate_per_kg,shipment_weight_kg,shipment_date,order_reference,invoice_number,remarks,delivery_status,delivered_at,expected_delivery_at) SELECT l.id,t.id,10000,3.80,10000,CURRENT_DATE-7,'DUMMY-ORDER-2','DUMMY-INV-2','Second dummy completed shipment','Delivered',now()-interval '6 days',now()-interval '5 days' FROM l,t;
INSERT INTO logistics_cost_register(shipment_id,order_reference,invoice_number,freight_cost,door_delivery_charges,porter_charges,other_charges,remarks) SELECT id,order_reference,invoice_number,38000,1800,750,450,'Second dummy actual cost' FROM logistics_shipments WHERE order_reference='DUMMY-ORDER-2';
INSERT INTO logistics_quotes(lane_id,transporter_id,quantity_kg,quoted_freight_per_kg,awarded,remarks,quoted_at)
SELECT s.lane_id,s.transporter_id,10000,4.10,TRUE,'Dummy awarded market quotation',now()-interval '8 days' FROM logistics_shipments s WHERE s.order_reference='DUMMY-ORDER-2';
COMMIT;
